### ISSUE TITLE
Discord stuck on loading screen

### ISSUE THREAD

**Issue by lexj88** [getstation/desktop-app#10]
New to Github, apologies.

I downloaded the Station version linked in the email, and I'm running macOS Big Sur 11.5. 

Tried deleting the Discord instance and starting over, but when I re-add a Discord instance back into Station, it's still frozen on the same loading screen (spinning controller logo with 'did you know' banners beneath - and not spinning, or cycling through banners).

Hope this is of some use to someone!

**Comment by MeguminSama** [comment]
Websockets appear to be 404ing when using the app.

This applies to the main gateway, and the authentication gateway.

![image](https://user-images.githubusercontent.com/27697325/125883396-572f9194-a309-44c5-8e34-6a2080a8d924.png)

**Comment by HectoFR** [comment]
Same here with the 2.0.9 😢 

(and the qrcode wasn't showing too)

**Comment by Mikee133** [comment]
As of Dec 15th, its still not working.
