### ISSUE TITLE
MACOS MONTEREY

### ISSUE THREAD

**Issue by amerinoalegre** [getstation/desktop-app#100]
Hello.
Station don't work with macOS Monterey.
Is there any solution?

**Comment by pixeline** [comment]
Specify "don't work" otherwise no one can reproduce your bug. 
I'm on Monterey and it installed correctly. Twitter and LinkedIn work. WhatsApp, Discord don't.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
