### ISSUE TITLE
Install problem on Linux

### ISSUE THREAD

**Issue by Smithbc** [getstation/desktop-app#102]
Hello, I entered the Terminal command for Linux Ubuntu on my Librem 14 running PureOS (Debian based) and it seemed to install, but I cannot find an icon for Station. Wondering if I did something wrong or if I'm missing something. Here is my Terminal info in case that helps. Thank you. : 

bsmith@PapasDragon:~$ sudo apt install graphicsmagick icnsutils libxtst-dev libx11-dev libxrender-dev libxkbfile-dev libgconf-2-4
[sudo] password for bsmith: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libgconf-2-4 is already the newest version (3.2.6-7).
libgconf-2-4 set to manually installed.
The following packages were automatically installed and are no longer required:
  ftp info libboost-date-time1.71.0 libboost-filesystem1.71.0
  libboost-iostreams1.71.0 libboost-locale1.71.0 libboost-thread1.71.0
  libbotan-2-17 libcapstone3 libcdio-cdda2 libcdio-paranoia2
  libedataserver-1.2-24 libjsoncpp1 libllvm10 libperl5.30 libphonenumber7
  libplymouth4 libpython3.8 libpython3.8-minimal libpython3.8-stdlib
  libreadline5 libsane libtepl-4-0 libtspi1 libxcb-util0 libxenmisc4.11
  lightning papirus-icon-theme perl-modules-5.30 python3-gpg python3-tdb
  python3.8 python3.8-minimal samba-common thunderbird ufw
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libgraphicsmagick-q16-3 libicns1 libpthread-stubs0-dev libxau-dev
  libxcb1-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev x11proto-dev
  x11proto-input-dev x11proto-record-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
Suggested packages:
  graphicsmagick-dbg libx11-doc libxcb-doc libxext-doc
The following NEW packages will be installed:
  graphicsmagick icnsutils libgraphicsmagick-q16-3 libicns1
  libpthread-stubs0-dev libx11-dev libxau-dev libxcb1-dev libxdmcp-dev
  libxext-dev libxfixes-dev libxi-dev libxkbfile-dev libxrender-dev
  libxtst-dev x11proto-dev x11proto-input-dev x11proto-record-dev
  x11proto-xext-dev xorg-sgml-doctools xtrans-dev
0 upgraded, 21 newly installed, 0 to remove and 49 not upgraded.
Need to get 4,585 kB of archives.
After this operation, 16.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://repo.pureos.net/pureos byzantium/main amd64 libgraphicsmagick-q16-3 amd64 1.4+really1.3.36+hg16481-2 [1,167 kB]
Get:2 http://repo.pureos.net/pureos byzantium/main amd64 graphicsmagick amd64 1.4+really1.3.36+hg16481-2 [1,010 kB]
Get:3 http://repo.pureos.net/pureos byzantium/main amd64 libicns1 amd64 0.8.1-3.1 [36.9 kB]
Get:4 http://repo.pureos.net/pureos byzantium/main amd64 icnsutils amd64 0.8.1-3.1 [25.6 kB]
Get:5 http://repo.pureos.net/pureos byzantium/main amd64 libpthread-stubs0-dev amd64 0.4-1 [5,344 B]
Get:6 http://repo.pureos.net/pureos byzantium/main amd64 xorg-sgml-doctools all 1:1.11-1.1 [22.1 kB]
Get:7 http://repo.pureos.net/pureos byzantium/main amd64 x11proto-dev all 2020.1-1 [594 kB]
Get:8 http://repo.pureos.net/pureos byzantium/main amd64 libxau-dev amd64 1:1.0.9-1 [22.9 kB]
Get:9 http://repo.pureos.net/pureos byzantium/main amd64 libxdmcp-dev amd64 1:1.1.2-3 [42.2 kB]
Get:10 http://repo.pureos.net/pureos byzantium/main amd64 xtrans-dev all 1.4.0-1 [98.7 kB]
Get:11 http://repo.pureos.net/pureos byzantium/main amd64 libxcb1-dev amd64 1.14-3 [176 kB]
Get:12 http://repo.pureos.net/pureos byzantium/main amd64 libx11-dev amd64 2:1.7.2-1 [841 kB]
Get:13 http://repo.pureos.net/pureos byzantium/main amd64 x11proto-xext-dev all 2020.1-1 [3,404 B]
Get:14 http://repo.pureos.net/pureos byzantium/main amd64 libxext-dev amd64 2:1.3.3-1.1 [107 kB]
Get:15 http://repo.pureos.net/pureos byzantium/main amd64 libxfixes-dev amd64 1:5.0.3-2 [24.1 kB]
Get:16 http://repo.pureos.net/pureos byzantium/main amd64 x11proto-input-dev all 2020.1-1 [3,412 B]
Get:17 http://repo.pureos.net/pureos byzantium/main amd64 libxi-dev amd64 2:1.7.10-1 [242 kB]
Get:18 http://repo.pureos.net/pureos byzantium/main amd64 libxkbfile-dev amd64 1:1.1.0-1 [86.2 kB]
Get:19 http://repo.pureos.net/pureos byzantium/main amd64 libxrender-dev amd64 1:0.9.10-1 [40.8 kB]
Get:20 http://repo.pureos.net/pureos byzantium/main amd64 x11proto-record-dev all 2020.1-1 [3,408 B]
Get:21 http://repo.pureos.net/pureos byzantium/main amd64 libxtst-dev amd64 2:1.2.3-1 [31.9 kB]
Fetched 4,585 kB in 5s (854 kB/s)       
Selecting previously unselected package libgraphicsmagick-q16-3.
(Reading database ... 290262 files and directories currently installed.)
Preparing to unpack .../00-libgraphicsmagick-q16-3_1.4+really1.3.36+hg16481-2_am
d64.deb ...
Unpacking libgraphicsmagick-q16-3 (1.4+really1.3.36+hg16481-2) ...
Selecting previously unselected package graphicsmagick.
Preparing to unpack .../01-graphicsmagick_1.4+really1.3.36+hg16481-2_amd64.deb .
..
Unpacking graphicsmagick (1.4+really1.3.36+hg16481-2) ...
Selecting previously unselected package libicns1:amd64.
Preparing to unpack .../02-libicns1_0.8.1-3.1_amd64.deb ...
Unpacking libicns1:amd64 (0.8.1-3.1) ...
Selecting previously unselected package icnsutils.
Preparing to unpack .../03-icnsutils_0.8.1-3.1_amd64.deb ...
Unpacking icnsutils (0.8.1-3.1) ...
Selecting previously unselected package libpthread-stubs0-dev:amd64.
Preparing to unpack .../04-libpthread-stubs0-dev_0.4-1_amd64.deb ...
Unpacking libpthread-stubs0-dev:amd64 (0.4-1) ...
Selecting previously unselected package xorg-sgml-doctools.
Preparing to unpack .../05-xorg-sgml-doctools_1%3a1.11-1.1_all.deb ...
Unpacking xorg-sgml-doctools (1:1.11-1.1) ...
Selecting previously unselected package x11proto-dev.
Preparing to unpack .../06-x11proto-dev_2020.1-1_all.deb ...
Unpacking x11proto-dev (2020.1-1) ...
Selecting previously unselected package libxau-dev:amd64.
Preparing to unpack .../07-libxau-dev_1%3a1.0.9-1_amd64.deb ...
Unpacking libxau-dev:amd64 (1:1.0.9-1) ...
Selecting previously unselected package libxdmcp-dev:amd64.
Preparing to unpack .../08-libxdmcp-dev_1%3a1.1.2-3_amd64.deb ...
Unpacking libxdmcp-dev:amd64 (1:1.1.2-3) ...
Selecting previously unselected package xtrans-dev.
Preparing to unpack .../09-xtrans-dev_1.4.0-1_all.deb ...
Unpacking xtrans-dev (1.4.0-1) ...
Selecting previously unselected package libxcb1-dev:amd64.
Preparing to unpack .../10-libxcb1-dev_1.14-3_amd64.deb ...
Unpacking libxcb1-dev:amd64 (1.14-3) ...
Selecting previously unselected package libx11-dev:amd64.
Preparing to unpack .../11-libx11-dev_2%3a1.7.2-1_amd64.deb ...
Unpacking libx11-dev:amd64 (2:1.7.2-1) ...
Selecting previously unselected package x11proto-xext-dev.
Preparing to unpack .../12-x11proto-xext-dev_2020.1-1_all.deb ...
Unpacking x11proto-xext-dev (2020.1-1) ...
Selecting previously unselected package libxext-dev:amd64.
Preparing to unpack .../13-libxext-dev_2%3a1.3.3-1.1_amd64.deb ...
Unpacking libxext-dev:amd64 (2:1.3.3-1.1) ...
Selecting previously unselected package libxfixes-dev:amd64.
Preparing to unpack .../14-libxfixes-dev_1%3a5.0.3-2_amd64.deb ...
Unpacking libxfixes-dev:amd64 (1:5.0.3-2) ...
Selecting previously unselected package x11proto-input-dev.
Preparing to unpack .../15-x11proto-input-dev_2020.1-1_all.deb ...
Unpacking x11proto-input-dev (2020.1-1) ...
Selecting previously unselected package libxi-dev:amd64.
Preparing to unpack .../16-libxi-dev_2%3a1.7.10-1_amd64.deb ...
Unpacking libxi-dev:amd64 (2:1.7.10-1) ...
Selecting previously unselected package libxkbfile-dev:amd64.
Preparing to unpack .../17-libxkbfile-dev_1%3a1.1.0-1_amd64.deb ...
Unpacking libxkbfile-dev:amd64 (1:1.1.0-1) ...
Selecting previously unselected package libxrender-dev:amd64.
Preparing to unpack .../18-libxrender-dev_1%3a0.9.10-1_amd64.deb ...
Unpacking libxrender-dev:amd64 (1:0.9.10-1) ...
Selecting previously unselected package x11proto-record-dev.
Preparing to unpack .../19-x11proto-record-dev_2020.1-1_all.deb ...
Unpacking x11proto-record-dev (2020.1-1) ...
Selecting previously unselected package libxtst-dev:amd64.
Preparing to unpack .../20-libxtst-dev_2%3a1.2.3-1_amd64.deb ...
Unpacking libxtst-dev:amd64 (2:1.2.3-1) ...
Setting up libpthread-stubs0-dev:amd64 (0.4-1) ...
Setting up xtrans-dev (1.4.0-1) ...
Setting up libgraphicsmagick-q16-3 (1.4+really1.3.36+hg16481-2) ...
Setting up libicns1:amd64 (0.8.1-3.1) ...
Setting up xorg-sgml-doctools (1:1.11-1.1) ...
Setting up icnsutils (0.8.1-3.1) ...
Setting up graphicsmagick (1.4+really1.3.36+hg16481-2) ...
Processing triggers for sgml-base (1.30) ...
Processing triggers for mailcap (3.69) ...
Setting up x11proto-dev (2020.1-1) ...
Setting up libxau-dev:amd64 (1:1.0.9-1) ...
Processing triggers for libc-bin (2.31-13+deb11u2) ...
Processing triggers for man-db (2.9.4-2) ...
Setting up libxdmcp-dev:amd64 (1:1.1.2-3) ...
Setting up x11proto-input-dev (2020.1-1) ...
Setting up x11proto-xext-dev (2020.1-1) ...
Setting up x11proto-record-dev (2020.1-1) ...
Setting up libxcb1-dev:amd64 (1.14-3) ...
Setting up libx11-dev:amd64 (2:1.7.2-1) ...
Setting up libxfixes-dev:amd64 (1:5.0.3-2) ...
Setting up libxext-dev:amd64 (2:1.3.3-1.1) ...
Setting up libxi-dev:amd64 (2:1.7.10-1) ...
Setting up libxrender-dev:amd64 (1:0.9.10-1) ...
Setting up libxtst-dev:amd64 (2:1.2.3-1) ...
Setting up libxkbfile-dev:amd64 (1:1.1.0-1) ...

**Comment by Ralph-Fonz** [comment]
if you are just trying to install and use the app, just use the app image

**Comment by Smithbc** [comment]
OK. Thank you. Is there any way to install it so I can get automatic updates? Any way to integrate with my software center?
