### ISSUE TITLE
Google authentication not working, might be OAuth problems 

### ISSUE THREAD

**Issue by khuongduy354** [getstation/desktop-app#104]
I only use this app for the first time, it's great, but I would be even nicer if I could use my Gmail & Drive. 
## Issue 
When i click Add a new account from gmail in Station windows desktop app, it pops up the authentication page, i typed email and password it, and it redirects to this
![image](https://user-images.githubusercontent.com/42113313/149706516-54d908df-1ac6-4671-befe-d8df03b6e7aa.png)

- I used Notion ( logged in by Gmail ) and Microsoft todo ( microsoft account ) successfully, but Gmail and Google Drive didn't work

**Comment by benhbell** [comment]
I also replicated this issue on mac OSX

**Comment by jsanta** [comment]
Can confirm the same issue on Mac OS Catalina.

**Comment by khuongduy354** [comment]
https://github.com/getstation/desktop-app/issues/89#issuecomment-1012706636
The solution above fix this, but it raises a new problem of not able to choose the icons, and seems to be glitching. 
I think this app is no longer supported, so I switched to getFerdi, which is also open-source.

**Comment by jsanta** [comment]
@khuongduy354 I don't think (MHO)  a workaround may be enough to close an issue as the issue still exists. Agreed,  there's a way of solving the root requirement, but the OAuth problem when using  "the supposed to be available services" directly from the app, is still there.
