### ISSUE TITLE
Cannot add new apps

### ISSUE THREAD

**Issue by TheGhostStalker** [getstation/desktop-app#105]
I love Station. It saved my work-life pre pandemic. But now I cannot load new apps. The error is 105:ERR_NAME_NOT_RESOLVED.

From https://apps.getstation.com/#custom-apps

**Comment by nurse-the-code** [comment]
It appears that development is currently paused. There have not been any commits made in 6 months.

**Comment by TheGhostStalker** [comment]
Thank you for the response! Does this mean that Station is essentially no longer supported? It was superior to the browser-based dashboard apps :(

**Comment by nurse-the-code** [comment]
@TheGhostStalker I am not sure. I just discovered this app today. Since I was having some bugs with it, and noticed that it hadn't been updated, I looked for another app. I went with [Fredi](https://github.com/getferdi/ferdi) which seems to be more actively developed ATM and is also open source.
