### ISSUE TITLE
i need station app icon for desktop entry please help

### ISSUE THREAD

**Issue by Vignes07** [getstation/desktop-app#106]

**Comment by paulsybrandy** [comment]
I have uploaded the .ico file. When you go to it, it looks tiny for the preview but just click Download in the upper right corner and it will save the icon file.

https://fnlcmz-my.sharepoint.com/:i:/g/personal/user9009_fnlcmz_onmicrosoft_com/EcWGmFbrJgVLkOCi-qZPD7YBAprVP737s5lYDQXs0Q2I2A?e=AcQrn1
