### ISSUE TITLE
Gitlab will not load

### ISSUE THREAD

**Issue by juliusmong** [getstation/desktop-app#108]
It keeps saying it's checking for browser:
---
Checking your browser before accessing gitlab.com.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…
---

But it never loads, and eventually STation will throw a screen saying failed to load, try restarting, at whcih point if clicked station will crash.

I'm using Mac running Station 2.0.9
Electron7.3.3
Chrome78.0.3904.130
Node12.8.1
v87.8.279.23-electron.0

**Comment by pvojnisek** [comment]
Same here running Pop!_OS

But this application is not maintained anymore.. :(

**Comment by viktor44** [comment]
Login page is shown in Electron 24.2.0
