### ISSUE TITLE
Can't log into Google Account

### ISSUE THREAD

**Issue by mstephen19** [getstation/desktop-app#112]
Receiving this when adding a new account:

```
Error 400: invalid_request
Missing required parameter: client_id
```

**Comment by Smodi1017** [comment]
I’m having the same problem while adding Gmail account!!!

**Comment by safurrier** [comment]
I'm also having this issue

**Comment by Erdemaydo** [comment]
same here

**Comment by BlossomNyx** [comment]
Same Here

**Comment by Ulipenitz** [comment]
Same here

**Comment by sujayghosh** [comment]
I am also facing the same issue

**Comment by jonathanwsl** [comment]
same here, and the site stationhq is also not accessible

**Comment by mbaumel22** [comment]
same here, following for fixes

**Comment by jonathanwsl** [comment]
I manage to go around by linking the gmail URL to the customise link.

**Comment by jasoncmcg** [comment]
OK, it looks like if you do the following, it will work:

- Click the plug on the bottom left
- Click 'Add a custom app' on the top right
- Type the name you want, click next
- Click 'Add' after the list
- Select a color and icon
- Paste the url: https://mail.google.com/mail/u/0/#inbox

Now, when you open the app, it will not try to use your default browser. It will auth in-app and work.

**Comment by mstephen19** [comment]
Instead of using a workaround, try this out https://getferdi.com/. Same exact thing pretty much
