### ISSUE TITLE
Question of all questions: Will Station be continued?

### ISSUE THREAD

**Issue by kNsja5w** [getstation/desktop-app#113]
It's sad reading all these issues without getting any answers. So: Are there plans with Station?

**Comment by RDKRACZ** [comment]
https://github.com/getstation/desktop-app/commit/f4c2de9c1c7e44cc0e522e7e19a518134f2fa088

**Comment by Petingo** [comment]
This is sad. This is an awesome APP.

Also, I thought all the problem could be fixed by upgrading the Electron version, so I cloned it and try.
But things didn't go well like there were so many error when upgrading.

I wish I knew how Electron works :(
