### ISSUE TITLE
Gmail not working

### ISSUE THREAD

**Issue by suhailsinghbains** [getstation/desktop-app#114]
I am a new user here, I tried to add my Gmail account to the station and this is not working, can you please help me out? 

PS - I tried to copy link into Chrome, still no good

<img width="470" alt="Screen Shot 2022-03-21 at 8 51 57 AM" src="https://user-images.githubusercontent.com/10033914/159264943-203ff140-2c29-436b-893c-2c3509477644.png">

**Comment by jacob-squires** [comment]
LOL this is ridiculous. The most intriguing point of this software as an alternative to Shift was being able to have all my gmail accounts in one spot. Not even able to test this out. Oh well.

**Comment by vyquocvu** [comment]
This is same issue i got.
Try work around a "Custom app"
URL: https://myaccount.google.com
<img width="1440" alt="Screenshot 2022-11-15 at 13 39 10" src="https://user-images.githubusercontent.com/13213996/201847198-32a0f391-3fc6-4424-9885-1ffcc26133ed.png">

Click on Email Icon to navigate to email tab, done!
<img width="1440" alt="Screenshot 2022-11-15 at 13 39 46" src="https://user-images.githubusercontent.com/13213996/201846468-72fed407-85d9-403f-86e4-8d7529f070d3.png">

// Drive and Calendar are the same!
