### ISSUE TITLE
Update Browser Version — Chrome? I think

### ISSUE THREAD

**Issue by hdavidviloria** [getstation/desktop-app#120]
Is there any way to update the browser that Station uses? For example, when i log into telegram, it says it's logged in Chrome 78, which has quite a lot of security vulnerabilities. When I also go to whatismybrowser.com through Station, it shows me that chrome is version 78. Is there a workaround to update chrome?

<img width="806" alt="Screen Shot 2022-04-18 at 9 05 09 AM" src="https://user-images.githubusercontent.com/94162758/163739399-b8f4aa58-0171-4990-a7ea-31298b374a50.png">

**Comment by trickypr** [comment]
I am currently working on upgrading the version of electron (the chromium provider) on a separate fork. If I ever get it to work, I will open a pull request
