### ISSUE TITLE
Is Station shutting down? Which app should we use instead?

### ISSUE THREAD

**Issue by robwired** [getstation/desktop-app#121]
There are multiple threads about Station no longer working with Google sign-in which makes it effectively useless for anyone who either uses Google apps or signs on with Google. That affects almost everyone.

There hasn't been any reply on the message boards about these issues so can we assume Station is shutting down?

If so, what apps should we migrate to?

**Comment by u6tory** [comment]
Ferdium is cool but searching for every app is not available.

**Comment by natrius** [comment]
Just in case someone else stumbles on this

- https://github.com/albertlauncher/albert
- https://github.com/Wox-launcher/Wox
- https://github.com/cerebroapp/cerebro

Thats what i found thats somewhat active.

**Comment by natrius** [comment]
I'm confused, so its a live again? A comment would be amazing ^^ Its closed as not planned but at the same time there is 2.1.0. But the readme is still "not active, just PR"
