### ISSUE TITLE
Email verification does not work

### ISSUE THREAD

**Issue by kolaente** [getstation/desktop-app#128]
Hi!

I'm trying to use station and signed up for an account. After that, it told me to verify my email address by clicking the link I received via mail. The problem with that is I never received an email with a verification link. I looked in my mailserver's logs and it looks like the server never even received it, so it's not just in the spam folder or anything.

The console running station has a lot of errors like this one:

```
[17:29:33.383] [error] LaunchDarklyUnexpectedResponseError: environment not found. Please see https://docs.launchdarkly.com/docs/js-sdk-reference#section-initializing-the-client for instructions on SDK initialization.
```

Not sure if this is related to my problem though.

Apart from that, why do I need an account to use station?

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
