### ISSUE TITLE
/macOS/ no qr code shown for whatsapp and telegram? chrome updated to the last version.

### ISSUE THREAD

**Issue by GaHub** [getstation/desktop-app#129]
as per the title it seems like I can't see the qr code to configure whatsapp and telegram. any help?

**Comment by mzamora007** [comment]
I am having the same issue. Also Discord and Teams won't load. I just installed the app so it's not a cache issue.

**Comment by calabro** [comment]
Fresh install, same issue.  No QR for Discord or Whatsapp.

**Comment by aloxe** [comment]
Same issue on fresh install. I see a network error with this call:
```
Request URL: wss://web.whatsapp.com/ws/chat
Request Method: GET
Status Code: 400 Bad Request
```

**Comment by skyedream** [comment]
same here whatsapp not showing QR code. also, the google hangout showing "whoops, sorry, google chat is not supported on your current browser."
