### ISSUE TITLE
No actual multi-account support.

### ISSUE THREAD

**Issue by tribbloid** [getstation/desktop-app#131]
To enable this feature, each app & extension has to use its own cookie cache, web cache & password/credential vault.

I don't think this is supported natively, comparing to Franz or Biscuit. At this moment, login into another Gmail account in the second Gmail instance will override the automatic login of the first Gmail instance.

How hard does it take to support it?

**Comment by noma4i** [comment]
Would be nice to see that cookiejar to be implemented.
