### ISSUE TITLE
Adding Gmail account throws error

### ISSUE THREAD

**Issue by taamrove** [getstation/desktop-app#134]
When trying to add gmail account, when logging into account I get "missing client_id".

I guess something is wrong?

**Comment by LenaRobin** [comment]
same here with all google apps (calendar etc)

**Comment by JamesS-M** [comment]
I'm running into this issue as well.

**Comment by e-cruzz** [comment]
Same here, this is the error I am receiving:
![error](https://user-images.githubusercontent.com/105756742/193701948-f6f6d8e6-7ea4-4587-bd74-8adfa1641c38.jpg)

**Comment by edi1973** [comment]
Same here. The Windows version is 
Windows 11 Pro 21H2 Build 22000.1042 licensed
for Station is
![image](https://user-images.githubusercontent.com/20280652/195535937-98364814-6361-4cf1-96b8-1e838085de06.png)

**Comment by rechungpa** [comment]
MacOS Monterey does not work as well with google accounts

**Comment by taamrove** [comment]
Issue here is that the developer removed their API keys from the app :/

tor. 13. okt. 2022, 14:00 skrev rechungpa ***@***.***>:

**Comment by rechungpa** [comment]
Thank you - and this will change for better - an update with the api keys?

**Comment by rechungpa** [comment]
Is there anybody still developing the station?

**Comment by ldelaprade** [comment]
Switching to https://github.com/TheGoddessInari/hamsket
not as nice as Station... but at least, it works
