### ISSUE TITLE
Brew Package

### ISSUE THREAD

**Issue by mayurankv** [getstation/desktop-app#136]
Would it be possible to package this as a homebrew cask for ease of downloading?

(Note opened a new issue from the [Linux Packaging Issue](https://github.com/getstation/desktop-app/issues/94) as Mac users are only able to use homebrew as opposed to the other mentioned package managers.)

**Comment by thelegend09** [comment]
Did you see that the [project is no longer actively maintained](https://github.com/getstation/desktop-app#readme)? :(

**Comment by viktor44** [comment]
#94
