### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by stimsonm** [getstation/desktop-app#137]
im trying to connect gmail for the first time and i get this when i login 

Authorization Error
Error 400: invalid_request
Missing required parameter: client_id

any idea whats going on?

**Comment by ldelaprade** [comment]
Same issue for me (on windows). Even when default browser is Chrome.

**Comment by ghubahmed** [comment]
Anyone figure this out yet?

**Comment by igorcaldeira** [comment]
same here :(

**Comment by willbod** [comment]
Me too

**Comment by sundowatch** [comment]
Same here

**Comment by zeussesions** [comment]
Same issue, just a 404 response.
