### ISSUE TITLE
Google Sign-in to Apps - Browser or App may not be secure

### ISSUE THREAD

**Issue by ripkurrle** [getstation/desktop-app#14]
I just downloaded the app today but unfortunately I've not been able to login to Slack or Trello using Google sign-in. An error is displayed saying

"
Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
"

Replication Steps
1) Open Station
2) Add in either Trello or Slack
3) Select to login using Google sign in
4) Enter your email address
Actual - Error presented
Expected - Able to enter password to sign in

It may be related to https://github.com/getstation/desktop-app/issues/2 but I think its sufficiently different to warrant a separate issue.

![image](https://user-images.githubusercontent.com/19253405/125826577-e0dbc46d-7c90-4bf4-9948-fe31a5a727e5.png)

**Comment by sven-ahrens** [comment]
This Issue is already known: https://github.com/getstation/desktop-app/issues/2 || https://github.com/getstation/desktop-app/issues/9

**Comment by ripkurrle** [comment]
Thanks @sven-ahrens , I close this
