### ISSUE TITLE
Google Calendar login invalid_request

### ISSUE THREAD

**Issue by TybuRak** [getstation/desktop-app#140]
Downloaded. Selected Google Calendar.  Selected "Add a new account". Redirected to browser to log in to google. Onced logged in:
Missing required parameter: client_id
400: invalid_request
![image](https://user-images.githubusercontent.com/46684451/210175830-c688b071-e915-4595-9c0c-90f20b4ed76c.png)

**Comment by TybuRak** [comment]
Checked. Same for google drive

**Comment by TybuRak** [comment]
![image](https://user-images.githubusercontent.com/46684451/210176098-cc73f604-5dc0-4cd6-8a26-ad7cebcce880.png)

**Comment by igorcaldeira** [comment]
same here :(

**Comment by MomoMiles** [comment]
Same here. If I have the time ill do a fork and look into it myself.

**Comment by msaiko239** [comment]
Has anyone found a resolution for this one?

**Comment by BlankB333** [comment]
Same here, Any work arounds?

**Comment by sarah5024** [comment]
Copied from another thread and it enabled  me to add gmail/google calender/google drive:
Create new "app" and insert the link -> https://myaccount.google.com/ after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

**Comment by viktor44** [comment]
This bug is fixed [here](https://github.com/viktor44/station-desktop-app/releases)
