### ISSUE TITLE
Facebook Messenger logs in succesfully than presents blank screen

### ISSUE THREAD

**Issue by redguar** [getstation/desktop-app#143]
Tried reinstalling Station twice on Windows, each time removing both Local and Roaming files.
I used Station before and did not have any issue.
Now i see Messenger page, asks for me for login and password, I tick "remember me", and then its just a total white screen.

Other apps work (like LinkedIn and Twitter for example)

**Comment by redguar** [comment]
<img width="1879" alt="Screenshot_47" src="https://user-images.githubusercontent.com/65287246/226062583-4e027283-d98c-4bff-aab0-31eb87233833.png">

**Comment by viktor44** [comment]
Start page is visible with Electron 24.2.0

**Comment by junefish** [comment]
> Start page is visible with Electron 24.2.0
My Station is using Electron 13.6.9, how can I upgrade it?

**Comment by viktor44** [comment]
It is necessary to migrate the code of Station to work with the new Electron.
Feel free to make a PR.

**Comment by jstrupek** [comment]
@viktor44 Have same question - how do I upgrade it? Not savvy enough at that level to do that without some simple instruction.

**Comment by littlepeon** [comment]
Need a simple how-to instruction guide. Or can we get the AppImage updated???? Seems to be an ongoing issue as you have a label for it, and have seen posts here from 2020, 2021 and 2022.
