### ISSUE TITLE
Teams - We are sorry we've run into an issue

### ISSUE THREAD

**Issue by ginolegigot** [getstation/desktop-app#145]
![image](https://user-images.githubusercontent.com/58557862/231809866-a0b10c9c-4fb3-43de-ac53-44aac040df26.png)
Hello,
I discovered station today but found out that the private message display is not working and this error message is shown.
I dont reproduce this issue in a classic chrome browser with webapp Teams.
Any hints ?

**Comment by viktor44** [comment]
#80
