### ISSUE TITLE
Unable to login G email

### ISSUE THREAD

**Issue by Kaavian** [getstation/desktop-app#149]
I'm trying to log in to my G Suite Gmail account and every time it says "Authentication error" and "client_id" is missing. Attaching a screenshot for reference.
![Screenshot 2023-05-09 at 11 37 47 AM](https://user-images.githubusercontent.com/21007030/237008960-35dee0a6-fc2a-41cc-aef3-60c988de0cf5.png)

**Comment by Kaavian** [comment]
> 

I downloaded the app. I'm not sure the version, I deleted it. I'm having Mac

**Comment by viktor44** [comment]
We've built MacOS release. You can try [it](https://github.com/getstation/desktop-app/releases/tag/v2.1.0).
