### ISSUE TITLE
Slack doesn't update until I manually refresh

### ISSUE THREAD

**Issue by jupman** [getstation/desktop-app#15]
Been using the former version of Station for some time on macOS. I'm a big fan. All good (save for memory usage!).

Following the recent announcement about that version being retired, I downloaded the newest version on GitHub.

I've tried to re-add my accounts with very limited success:

1) Slack doesn't appear to update with new messages received -- I have to manually refresh (Cmd+R on macOS) to see any new messages.

2) WhatsApp, Telegram & Discord do not display the QR code for me to scan with my phone to reconnect (I gather others have reported this bug separately)

Please fix, I'm lost without this app.

In the meantime, does anyone know what version I can downgrade to to get it all working again quickly?

**Comment by quangngotan95** [comment]
I got the same issue, @jupman downgrading to Canary 0.19 works for me https://github.com/getstation/station-canary/releases

**Comment by jupman** [comment]
> I got the same issue, @jupman downgrading to Canary 0.19 works for me https://github.com/getstation/station-canary/releases

Thank you, this works 100%. Really appreciate your feedback. As a non-technical user, I had no idea how to use GitHub!

**Comment by huysbs** [comment]
+1
Would be nice to have this fixed this in the 2.x version

**Comment by viktor44** [comment]
1. Duplicate #25 
2. Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
