### ISSUE TITLE
Facebook Messenger and Instagram blank screen

### ISSUE THREAD

**Issue by vzenzo** [getstation/desktop-app#151]
Logged into Wapp and Discord with no issues
But Facebook apps like Messenger and Instagram just give blank white screen, there is not even way to log in

**Comment by xalt7x** [comment]
Possibly related to #143

**Comment by littlepeon** [comment]
seems to be related to outdated electron. I too am experiencing this with Instagram. Need a simple guide to update Electron version within AppImage.

**Comment by worryboy** [comment]
Electron isn't outdated :

```
xx@MacBookAir ~ % npm show electron version
24.4.0
```

how you state or find out that electron is outdated ?

**Comment by littlepeon** [comment]
"current version" of this app is 2.1. Going to it's "about station" tab states that it was built with Electron 13.6.9 and Chrome 91.0.4472.164 Node 14.16.0 and v8 9.1.269.40-electron.0. As I sandbox this AppImage, I have no problem with running "outdated" Electron/Chrome, my problem is that it no longer works with Facebook and Instagram. Electron 13.x was released May 2021 and is no longer supported. The current Electron is ver.24 and the last supported ver.22(End of Life July 2023, with ver.21 End of Life April 2023). I have read elsewhere that developers were having issues with ver.15/17 plug-ins. I have no experience updating "parts" of AppImages, Snaps. or Flatpaks, even though has been stated elsewhere that it can be done. I understand that developers have other issues (work, life, other projects) and appreciate all that they do--- I was just asking for a guide on how to resolve this issue myself-- If that is not viable, I will await further releases.

**Comment by bsadasdso** [comment]
installed the latest electron but station is lagging anyway//
![scsc](https://github.com/getstation/desktop-app/assets/134848145/a672aa9b-dd72-4b79-981f-712d17de094e)
