### ISSUE TITLE
Broken Links on MacOS App

### ISSUE THREAD

**Issue by worryboy** [getstation/desktop-app#152]
Bad/Broken  Links ;

under menu "Help"
_**FAQ**_ links to "https://intercom.help/station"
_**Bug and Feature Request**_ links to "https://feedback.getstation.com" 
_**Privacy Policies**_ links to "https://intercom.help/station/data-and-privacy/station-privacy-policies"
_**Discover station features**_ links to "NONE"

**Comment by worryboy** [comment]
finde more 
under "about Station" 

**_About Station_** links to "https://medium.com/getstation/your-way-of-working-belongs-to-the-stone-age-9ff64782f40"
**_Support_** links to "https://intercom.help/station"

**Comment by BrianLz** [comment]
> finde more under "about Station"
> 
> **_About Station_** links to "https://medium.com/getstation/your-way-of-working-belongs-to-the-stone-age-9ff64782f40" **_Support_** links to "https://intercom.help/station"

- Medium link not broken
- Support link changed in PR #155
