### ISSUE TITLE
[macOS] changed code-signature on 2.1 release

### ISSUE THREAD

**Issue by core-code** [getstation/desktop-app#156]
previous releases were signed by

`Joel Charles (5D95778L6J)
`
but the new version is signed by

`Viktor Kadachigov (6ZT9HVU37U)
`
is this a valid/official release and the changed signature is expected, or have the uploaded binaries been tampered with?

**Comment by viktor44** [comment]
@magne4000 what do you think?

**Comment by magne4000** [comment]
I no longer have access to my Certificate for some time.
@viktor44 joined Station's maintainers and is the one that created the new MacOS build.
And as I have no longer access to my original Certificate, we cannot have a double-signed build to ease the transition sadly.

tldr; It's to be expected, the binaries are fine!

**Comment by core-code** [comment]
thanks for the confirmation!
