### ISSUE TITLE
Google Chat has deprecated name and icon

### ISSUE THREAD

**Issue by viktor44** [getstation/desktop-app#158]
It still has the name Hangouts and old icon.

![image](https://github.com/getstation/desktop-app/assets/8362098/9e895b82-daaa-4fe6-a756-95b57e900089)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by tarunsamanta2k20** [comment]
what should be the replacement instead of Hangouts?

**Comment by viktor44** [comment]
It's Google Chat now 
https://en.wikipedia.org/wiki/Google_Chat

You can find the icon here https://simpleicons.org/?q=google%20chat

**Comment by tarunsamanta2k20** [comment]
what should i put in cdn.filestackcontent.com?

**Comment by viktor44** [comment]
> what should i put in cdn.filestackcontent.com?

I think this URL isn't used anymore.

**Comment by tarunsamanta2k20** [comment]
> > what should i put in cdn.filestackcontent.com?
> 
> I think this URL isn't used anymore.

How will the icons get displayed? i mean from where will it fetch the icon?

**Comment by tarunsamanta2k20** [comment]
Either you have to upload that google chat icon to the fIlestackcontect CDN and send me the handle or one api key is needed for uploading.

**Comment by viktor44** [comment]
No need for this fix, since we already have Google Chat.
