### ISSUE TITLE
Outlook Email, Android Messages Loading to Blank Screen

### ISSUE THREAD

**Issue by k-r-chandran** [getstation/desktop-app#161]
This seems like it might be related to #151 and #143 - 

Outlook email and Android Messages both install correctly, but load to a blank screen. 

Android Messages: 

![image](https://github.com/getstation/desktop-app/assets/136371693/2536f795-e54c-44ad-983f-dd7c0486925f)

Outlook: 

![image](https://github.com/getstation/desktop-app/assets/136371693/c9b95694-8cd5-4d0f-9bc4-40497bb292dc)

Seems like this issue might be reoccurring across users and other apps. Could I get guidance for how to fix this?

**Comment by 0xBYTESHIFT** [comment]
same with facebook messenger, youtube, teams and instagram. just blank screen

**Comment by mikaduffer** [comment]
Same issue for me here

**Comment by francesmothrock** [comment]
Same here. Not sure how to fix.

**Comment by micoli** [comment]
Hello, same issue for `android messages` on `osx ventura 13.1 (22C65)` at least
