### ISSUE TITLE
WhatsApp Notifications not working on Windows 11

### ISSUE THREAD

**Issue by Gold-nice** [getstation/desktop-app#163]
#For some reason, whenever somebody sends me a whatsapp notification, it doesn't show up in the notification center in Windows 11. And when I check notification settings in the Settings app, station isn't even an option in the list. Leads me to believe this is a issue with station. 
Best wishes, 
Gold-Nice

**Comment by Marcel-NL1963** [comment]
Same here, I get a notification for WhatsApp in the Notification sidebar, but no badge in the taksbar. Can this be fixed, please?

Thanks in advance, Marcel

**Comment by viktor44** [comment]
#177
