### ISSUE TITLE
Custom app icon thumbnails are broken

### ISSUE THREAD

**Issue by libroraptor** [getstation/desktop-app#166]
<img width="385" alt="image" src="https://github.com/getstation/desktop-app/assets/130518279/9b005901-0952-441c-841d-a0c0ba2a34da">

Stationversion 2.1.0
Electron13.6.9
Chrome91.0.4472.164
Node14.16.0
v89.1.269.40-electron.0

Running on MacOS 11.7.7

**Comment by libroraptor** [comment]
I just upgraded the system install of Electron to 25.2.0 but Station sticks with the old version that it's packaged with.

**Comment by viktor44** [comment]
Duplicate #125

**Comment by libroraptor** [comment]
Resolved itself following an OS update today.
