### ISSUE TITLE
Mastodon app needs flexibility for server choice

### ISSUE THREAD

**Issue by libroraptor** [getstation/desktop-app#167]
The current Mastodon app is tied to mastodon.social – it needs to prompt the user for the server URL at the same time as prompting for login details.

**Comment by libroraptor** [comment]
Alternative solution: provide for custom icon uploads or some other way to select pre-existing icon for custom apps. Perhaps use a Unicode emoji typeface to broaden the range instead of having to draw icons.

This could also fix a problem with some other apps whose icons are confusing, e.g. Google Keep has a light bulb that doesn't communicate its name or function. A keep (in the architectural sense) may be a better alternative – this is called a "canting" device. Canting devices do not always cross well over language barriers.

**Comment by libroraptor** [comment]
The problem's still there: it still connects only to mastodon.social

<img width="516" alt="image" src="https://github.com/getstation/desktop-app/assets/130518279/1d5c02cd-dfcb-4369-82a7-a177aa486203">

**Comment by libroraptor** [comment]
Should I overwrite my current manifests 292 and 6286 install with the latest committed version to test? I'm too much of a user to know the right way to do it.

**Comment by magne4000** [comment]
> is it "bx_multi_instance_config" that lets the server be changed from mastodon.social to something else?

Yes

Just remove your current Mastodon app from Station, and add it again. It will now ask for a custom domain.

**Comment by magne4000** [comment]
As you wish, I'd keep it closed, all information are available in this issue now. We'll post a comment here once the release is published.

**Comment by libroraptor** [comment]
I confirm that it works.

The interface phrasing should be updated, though: it asks for the URL of a "self-hosted instance". It would be more inclusive, and more accurate, to say a "different instance" because the vast majority of mastodon users are not using self-hosted instances.
