### ISSUE TITLE
Which file should I download for installation on Windows 10 Pro 64-bit?

### ISSUE THREAD

**Issue by Melaineg** [getstation/desktop-app#175]
Which file should I download for installation on Windows 10 Pro 64-bit?
![2023-06-30 16_26_20-Release 2 2 1 · getstation_desktop-app — Mozilla Firefox](https://github.com/getstation/desktop-app/assets/90869229/aefbc4c1-d884-4aa0-947e-4ff6c2e38239)

**Comment by viktor44** [comment]
[Station-x64-Setup.exe](https://github.com/getstation/desktop-app/releases/download/v2.2.1/Station-x64-Setup.exe)

:)
