### ISSUE TITLE
Unable to use O365 App - Browser is a bit unusual

### ISSUE THREAD

**Issue by ChrisCapasso** [getstation/desktop-app#176]
When I add my Office 365 mail I get a pop up stating that my browser is a bit unusual, try to disable VPNs, adblockers, etc.  My account is managed by GoDaddy if that is important.

**Comment by viktor44** [comment]
I've checked Office 365 App right now. It looks fine
Please provide a screen shot 
Is it a fatal problem or just one time popup?
What version and OS ?

**Comment by ChrisCapasso** [comment]
I am enclosing a scereenshot.  It is fatal.  After closing the pop up it takes me back to the login page.  MacOS 13.4.1On Jul 5, 2023, at 8:50 AM, Viktor ***@***.***> wrote:I've checked Office 365 App right now. It looks fine Please provide a screen shot Is it a fatal problem or just one time popup? What version and OS ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
