### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by libroraptor** [getstation/desktop-app#177]
No notifications are coming through for apps, regardless of whether the "background activity" flag is set.

For some apps, the "background activity" slider is greyed out and seemingly stuck in the "on" state. I can't tell whether that is intentional. It is also not sending the notifications through.

**Comment by libroraptor** [comment]
I have been looking through the code and don't yet know enough to be able to diagnose or fix it. But I could likely help on user documentation or UI phrasing if that's where the need actually is.

**Comment by Nyanco-Kotohomu** [comment]
I am in the same state. No notification is coming on Mac (M1). OS13.4.1.

**Comment by rapturt9** [comment]
Yeah same for M1

**Comment by mcolinburch** [comment]
Ditto for me - no apps are triggering any notifications (ProtonMail, Gmail, Slack, Notion, others.)

System details:
  Model Identifier:	MacBookPro17,1
  Chip:	Apple M1
  Memory:	16 GB
  System Firmware Version:	8422.121.1
  macOS Ventura: 13.4.1(c)

**Comment by maxandersen** [comment]
was about to open issue as I just installed Station in hope it would work better than Ferdium - but yeah; zero notifications happening - its as if station is just showing each site i a separate tab with no special integration at all.

I have google chat, zulip, slack, github, google drive, facebook, WhatsApp enabled - and all are just dead silent.

**Comment by hahnmg** [comment]
Same here. Whatsapp come through, others don't. Instagram for example, background flag is set but nothing happens. 
No notification, no badge.
2.4.0 on macOS 13.5 (22G74)

**Comment by egabe** [comment]
Same here. Outlook,gmail no notification.  Background flag is set but nothing happens.
Linux
Station 2.4.0

**Comment by libroraptor** [comment]
I get audio notifications for Slack and Mastodon. But there is no visual indication of which app it's from – neither on the app icons nor a count or status indicator the notifications icon.

Mac Station 2.4.0

**Comment by youbzh** [comment]
I'm on a M1 pro system, MacOS 12.7, and I get sound from notifications, however, I don't get any notification badges. Enabling or disabling notifications (general and per app switches) doesn't seem to change the app's behavior in any way either.

**Comment by rzr8891** [comment]
Same issue as everyone else:
- the notification tab is always empty even when it shouldn't
- most apps do not give notifications: instagram, tinder, bumble
- Whatsapp does indeed send notifications to windows notification bar
- I don't know the expected behaviour but if the apps in the tray should get a bubble with number of notifications then everything is greyed out always

Windows10
![image](https://github.com/getstation/desktop-app/assets/155545496/8c58b2c4-f52c-43a4-91d3-d46deea4d633)
![image](https://github.com/getstation/desktop-app/assets/155545496/2dcee7a6-922f-47cc-8701-fcd1275a95e2)

**Comment by papypom** [comment]
Well, same here I suppose.

**Comment by rzr8891** [comment]
Still no update? Is this not such a common issue?

**Comment by HitLuca** [comment]
Same issue

**Comment by centauromax** [comment]
Same issue.

MacBook Pro
2,6 GHz Intel Core i7 6 
core AMD Radeon Pro 5300M 4 GB 
Intel UHD Graphics 630 1536 MB
32 GB 2667 MHz DDR4
C02D1017MD6V
Sonoma 14.5

**Comment by fcFn** [comment]
Likewise Win 10. Unfortunately, no notifications means there isn't much use for the application. Not complaining since it's free anyway and I appreciate the effort. Hope this will get fixed soon.

**Comment by MrLuxuryYacht** [comment]
Without a badge on the app in the dock or notifications of any kind working there really isn't any point to Station. Surprised that it's not part of the app from the getgo.
