### ISSUE TITLE
sha512 doesn't match for ARM64 dmg file

### ISSUE THREAD

**Issue by juil** [getstation/desktop-app#179]
From [`latest-mac.yml`](https://github.com/getstation/desktop-app/releases/tag/v2.2.1):
```
version: 2.2.1
  - url: Station-arm64.dmg
    sha512: wHCI9Yeoa1E9voDFykO19nNMzyyHOU9M+Hm4c/0x+fun96VOUDLAePtQqJFuTA3ib0dNz/f9JnrnDkCKqCztCw==
    size: 197603858
```

From terminal:
```term
shasum -a 512 Station-arm64.dmg
c07088f587a86b513dbe80c5ca43b5f6734ccf2c87394f4cf879b873fd31f9fba7f7a54e5032c078fb50a8916e4c0de26f474dcff7fd267ae70e408aa82ced0b  Station-arm64.dmg
```

**Comment by viktor44** [comment]
Why do you think that they have to be the same?

**Comment by juil** [comment]
> Why do you think that they have to be the same?

@viktor44 Is the sha512 not supposed to be a checksum for file integrity?

**Comment by viktor44** [comment]
I have no idea what those sums for. 
There is a signing procedure on MacOS. You probably want to read [this](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html)

**Comment by juil** [comment]
Okay, that's very different from what I thought it was.

A lot of free software will provide a [checksum](https://en.wikipedia.org/wiki/Checksum) to prove that the downloaded file is as expected.
