### ISSUE TITLE
MS Teams app opens as blank

### ISSUE THREAD

**Issue by pjm777** [getstation/desktop-app#186]
Hi,
I am not able to set up MS Teams - after adding the app, it just shows up as blank.
Even when I set Office 365 app and tried to launch MS Teams from there, it didn't work.
I found a previous bug that mentioned outdated Electron version, but I have higher one and it still doesn't work.
![image](https://github.com/getstation/desktop-app/assets/140606609/acd8e497-3fbe-4d38-bcb2-8e0c81398eda)

**Comment by viktor44** [comment]
#80
