### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by k-r-chandran** [getstation/desktop-app#190]
After the latest update, Station has been stuck on the "Your Station will be ready soon..." page no matter what I do. All applications are on that screen. And it will stay that way for hours. Not sure if this is a bug, or if I've done something wrongly.

**Comment by viktor44** [comment]
Hi. On what OS  do you run it?

**Comment by k-r-chandran** [comment]
macOS Ventura 13.4.1

**Comment by viktor44** [comment]
Check the file `~/Library/Logs/Station/log.log`
It probably contain the reason. Please put here if you find something.
I would recommend to clean Station data. To do it remove folder `~/Library/Application Support/Stationv2`
You have to add all application again afterwards.

**Comment by prasanjit101** [comment]
Facing the same issue. Initially it worked fine. After a day or two of use it is now showing the same message "Your station will be ready soon"

Relevant infos:
Mac OS ventura 13.5.1

<img width="1440" alt="Screenshot 2023-08-22 at 12 43 17 AM 1" src="https://github.com/getstation/desktop-app/assets/57594105/9d1095df-87c1-40d4-a795-d3b5cb306a1c">

**Comment by prasanjit101** [comment]
> Check the file `~/Library/Logs/Station/log.log` It probably
<img width="1440" alt="Screenshot 2023-08-22 at 3 45 10 PM" src="https://github.com/getstation/desktop-app/assets/57594105/651d1889-5f24-4a77-8cb2-8fbcd892cd55">
 contain the reason. Please put here if you find something. I would recommend to clean Station data. To do it remove folder `~/Library/Application Support/Stationv2` You have to add all application again afterwards.

Checked the log file. Attached a screenshot.
