### ISSUE TITLE
Feature Request: Dark mode for Facebook Messenger

### ISSUE THREAD

**Issue by lagerea** [getstation/desktop-app#196]
Coming from Franz it was relatively easy to use CSS in recipes to modify so that dark mode would work, here is a contributor for example: https://github.com/ducfilan/Dark-mode-Franz-Ferdi

It would be a really nice addition, please and thank you.

**Comment by arkayn71** [comment]
As a temporary workaround, you can load Facebook itself and then click on the Messenger icon and select see all in Messenger

**Comment by viktor44** [comment]
It looks like complete solution for this ticket not as a workaround.
It also applies to WhatsApp and Telegram.

From the other side, as I can see, CSS overriding is not widely used in Ferdium project too.
So I'm closing the ticket now, but we will be happy to review the PR if anybody implement it in Station.

**Comment by lagerea** [comment]
> As a temporary workaround, you can load Facebook itself and then click on the Messenger icon and select see all in Messenger

Taking it one step further, loading specifically: https://www.facebook.com/messages/
