### ISSUE TITLE
Workflowy Won't Load

### ISSUE THREAD

**Issue by Elwood4415** [getstation/desktop-app#197]
I have attempted to install Workflowy as an app, but it will not install. If I use the pre-installed app, it tells me that the page does not exist (the app is directing towards the wrong url), and the "Home" link does not do anything. If I try to install it as a custom app, it just tells me that the page will not load. I am attempting this on a Mac, if that makes any difference.

**Comment by viktor44** [comment]
Start page is incorrect. The right one is `https://workflowy.com/login/`
But then application crashes with error:

![image](https://github.com/getstation/desktop-app/assets/8362098/40c9afe9-802f-42fe-a044-d40286039f77)

**Comment by viktor44** [comment]
In the pure webview Workflowy loads without errors
