### ISSUE TITLE
Gmail (and other Google Auth apps) authorization error

### ISSUE THREAD

**Issue by sven-ahrens** [getstation/desktop-app#2]
I heard the news and replaced my old station client with the new open-source version.

Now I'm trying to get setup again and connecting my Gmail account but I can't make it work. No matter how often I try, I always get the same error message:

![Bildschirmfoto 2021-07-14 um 15 48 13](https://user-images.githubusercontent.com/18313443/125633825-bdb5d583-4f38-42d8-9bd8-e1be8bbed197.png)

Does anyone have the same issue or knows how to fix that? Thanks in advance.

**Comment by sven-ahrens** [comment]
**_Details:_**

I'm on macOS Big Sure 11.4 and I installed the newest version of Station, which was linked in the email (v2.0.9)

**Comment by kd5kij** [comment]
I'm experiencing the same issue on the windows version (v2.0.9 - linked in the email.) 

I've also noticed I encounter the same error when trying to authenticate in Google Keep.

**Comment by dipsard** [comment]
Same issue for macOS Big Sure 11.4 and macOS Sierra - also Google log-in  issue with Trello which thinks the browser is unsafe

**Comment by carolinadelatorremaldonado** [comment]
Same issue on macOS Big Sure 11.2, no access to Google tools.

**Comment by directionforward** [comment]
Same issue here, macOS 10.14.6

**Comment by justice-dazzle** [comment]
Same issue here. Windows 10 1909.

**Comment by ssandison** [comment]
A temporary work around for this is to create your own custom app and use the following URL:

https://mail.google.com/mail/u/0/#inbox

How to do it:

1. Click on the + icon in the bottom left
2. Select My Custom Apps from the left hand menu
3. Click on Add a custom app in the top right.
4. Give it a name like Gmail.
5. Click on the add button.
6. Enter a colour hex code you like. e.g. #000000 for black.
7. Select a logo like the mail logo.
8. Enter the following URL: https://mail.google.com/mail/u/0/#inbox
9. Click the add button.
10. Click the install now button.
11. Click on the app icon you selected from the left hand menu and log in with google account.

That should work until a fix can be sorted out.

**Comment by lievendegrauwe** [comment]
Same issue here, thanks for the temp workaround!

**Comment by mskonovalov** [comment]
Somehow it does work on the old version that I use
Station Canary version 0.19.131

**Comment by sven-ahrens** [comment]
> A temporary work around for this is to create your own custom app and use the following URL:
> 
> https://mail.google.com/mail/u/0/#inbox
> 
> How to do it:
> 
> 1. Click on the + icon in the bottom left
> 2. Select My Custom Apps from the left hand menu
> 3. Click on Add a custom app in the top right.
> 4. Give it a name like Gmail.
> 5. Click on the add button.
> 6. Enter a colour hex code you like. e.g. #0 for black.
> 7. Select a logo like the mail logo.
> 8. Enter the following URL: https://mail.google.com/mail/u/0/#inbox
> 9. Click the add button.
> 10. Click the install now button.
> 11. Click on the app icon you selected from the left hand menu and log in with google account.
> 
> That should work until a fix can be sorted out. It only works for one account at a time though.

Didn't work for me unfortunately. Google told me the browser I'm using is unsafe and refused to log me in.

**Comment by sven-ahrens** [comment]
This has probably something to do with this issue here: https://github.com/getstation/desktop-app/issues/9 but who knows--with such complexity--when this will be fixed

**Comment by dpatra** [comment]
It looks like the Client Id is not filled in the url. Incase that helps, I have the url that is missing client_id value. @ssandison 

accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fv2%2Fauth%3Faccess_type%3Doffline%26scope%3Dhttps%253A%252F%252Fwww.googleapis.com%252Fauth%252Fplus.me%2520profile%2520email%26redirect_uri%3Dhttp%253A%252F%252F127.0.0.1%253A42813%252Fcallback%26response_type%3Dcode%26**client_id%3D**&flowName=GlifWebSignIn&flowEntry=AddSession

**Comment by krunk4ever** [comment]
For now, I've reverted back to the old version 1.65.0 which I found here:
https://www.macupdate.com/app/mac/60202/station
https://mac.softpedia.com/get/Internet-Utilities/getStation.shtml

Note, 1.65.0 will stop working on 8.31

**Comment by directionforward** [comment]
@krunk4ever very helpful, thanks! Will need to find another solution after end of August.

**Comment by Joshstomp** [comment]
> A temporary work around for this is to create your own custom app and use the following URL:
> 
> https://mail.google.com/mail/u/0/#inbox
> 
> How to do it:
> 
> 1. Click on the + icon in the bottom left
> 2. Select My Custom Apps from the left hand menu
> 3. Click on Add a custom app in the top right.
> 4. Give it a name like Gmail.
> 5. Click on the add button.
> 6. Enter a colour hex code you like. e.g. #0 for black.
> 7. Select a logo like the mail logo.
> 8. Enter the following URL: https://mail.google.com/mail/u/0/#inbox
> 9. Click the add button.
> 10. Click the install now button.
> 11. Click on the app icon you selected from the left hand menu and log in with google account.
> 
> That should work until a fix can be sorted out. It only works for one account at a time though.

This worked for me, Calendar still does not work

**Comment by marisajackson** [comment]
@Joshstomp For Calendar, you can do the same thing and just use this URL: `https://calendar.google.com/calendar/u/0/r`

**Comment by zettaivanugen** [comment]
Any workarounds to have more than one Gmail account logged in at the same time?

**Comment by jounii** [comment]
Having same issue, not being able to use Gmail accounts at all. I have several and station has been the "email" client for me. 

Have to look some other ways, maybe just create own iframe style html file with the accounts as tabs and use through normal browser instance.

**Comment by 4ndygu** [comment]
Same issue  --  haven't found a workaround yet for multiple accounts :(

**Comment by Tuba2** [comment]
I (quite innocently) tried to edit the authorization link by pasting the Client ID for the previous version — 3D382046058303-cghjkl19vsm6deuc9cc336fdpev5f7jt.apps.googleusercontent.com — in the place where the current Client ID should be.

Authorization went through, and it even called back the app, but the authorized account wasn't recognized by Station.

I guess, then, a really easy temporary fix would be for the devs to provide us with the Client ID for the current version.

I don't know if it is a problem, as I'm just a beginner. Well established companies have disclosed their Client IDs, but I don't really know the impact of this decision on a small open source project.

**Comment by kpinegar2** [comment]
Same issue here, is there any update?

**Comment by Tuba2** [comment]
> > Same issue here, is there any update?
> 
> This is dead. Probably is an abandoned project, I would look for an alternative like pinning tabs in edge. Good luck!

Don't know about that. Last release was just a month ago. Let's hope the developers are just too busy to answer hahaha

**Comment by ssandison** [comment]
I don't think they can fix it. The reason being you need a client ID from
Google to access the APIs. Previously Station were presumably using their
account to get the keys for the API for the app. Now they have open sourced
it, they have removed their keys. Some of these Google APIs cost money
based on the amount of requests. Really they should have provided a way for
people to add their own API keys into the settings at the very least.

**Comment by just-at-uber** [comment]
One thing I discovered to enable other google apps is to use the nine dots app icon inside gmail to access drive, calendar etc.
it will open a new station tab with the correct app logged in.

**Comment by Smithbc** [comment]
Station, Any update here? This is a major issue.

**Comment by ssandison** [comment]
I think people have given up and switched to something like Stack. That’s what I’ve done and the experience is pretty similar.

**Comment by Smithbc** [comment]
Is Stack open source?

**Comment by ssandison** [comment]
I don’t think so. Station was opened source because it’s been abandoned. If you want to stick with it you will probably need to get an account for the google APIs that it needs to use and generate keys to connect to the APIs. I think that’s why it no longer works. It’s a lot of hassle if you’re just wanting something that works rather than to maintain it yourself.

**Comment by zettaivanugen** [comment]
Not open source but completely free for all users. You can donate money if
you want but they’re not needed! Give it a go :)

**Comment by NazzarenoGiannelli** [comment]
Here your open source alternative. Works great without affecting the pc performance.
Rambox: https://rambox.app/#home

**Comment by hofq** [comment]
> Here your open source alternative. Works great without affecting the pc performance. Rambox: https://rambox.app/#home

Rambox is not Open Source any more

**Comment by NazzarenoGiannelli** [comment]
There is always the Community Edition for that https://github.com/ramboxapp/community-edition

**Comment by NazzarenoGiannelli** [comment]
> 
> 
> 
> > Here your open source alternative. Works great without affecting the pc performance. Rambox: https://rambox.app/#home
> 
> Rambox is not Open Source any more

There is always the Community Edition for that https://github.com/ramboxapp/community-edition

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
