### ISSUE TITLE
Changed code signature in macOS v 2.4.0

### ISSUE THREAD

**Issue by suschizu** [getstation/desktop-app#204]
hello - I've received a warning that the code signature has changed between 2.3.0 and 2.4.0:

`EXPECTED 'Viktor Kadachigov (6ZT9HVU37U)' but FOUND 'Joel Charles (5D95778L6J)'`

can you confirm this @viktor44?

**Comment by viktor44** [comment]
Yes, of course. Joël is the owner of this repository.
