### ISSUE TITLE
Cannot join meetings from Google Chat Instances

### ISSUE THREAD

**Issue by RobLSofvie** [getstation/desktop-app#205]
When clicking meeting invites from a Google Chat instance a new window opens with a 500 error. Seems to work just fine when opening meeting links from Google Calendar.
![SCR-20230908-moim](https://github.com/getstation/desktop-app/assets/102529618/1539c428-794f-42f2-9a22-b163eae3ece2)

**Comment by viktor44** [comment]
#174
