### ISSUE TITLE
Clicking new "Open booking page" button in Google Calendar fails to open popup, app becomes unresponsive

### ISSUE THREAD

**Issue by elRafa** [getstation/desktop-app#209]
See attached screenshot: 
<img width="467" alt="Screenshot 2023-09-13 at 10 15 50 PM" src="https://github.com/getstation/desktop-app/assets/1198779/30951a96-e23a-42d9-8255-e9e3e40c1316">

**Comment by viktor44** [comment]
Google Calendar works fine for me.
Does this button open some external application?

**Comment by elRafa** [comment]
I'm referring specifically to the "Open booking page" button. It opens a new tab or window, and now seems to be working properly. I'll close this report.
