### ISSUE TITLE
App crashes more often

### ISSUE THREAD

**Issue by Kaavian** [getstation/desktop-app#211]
- Application version: 2.4.0
 - OS: MacOS Ventura 13.4.1 

**Steps to Reproduce:**
The app crashes very often. I recently added the Google Analytics app, and then the app crashed. It happens more often, for example when I click the email notification.
<img width="1439" alt="Screenshot 2023-09-15 at 5 59 27 PM" src="https://github.com/getstation/desktop-app/assets/21007030/dbcf1262-9443-4ba7-a821-b29600988854">

**Comment by viktor44** [comment]
By saying "app crashes" do you mean that this "Your Station will be ready soon"-page never ends?

**Comment by Kaavian** [comment]
> By saying "app crashes" do you mean that the "Your Station will be ready soon"-page never ends?
Yes. It's just stuck there.

> Check this [#203 (comment)](https://github.com/getstation/desktop-app/issues/203#issuecomment-1717353312) Is it your case?
The work around suggested helped me. But that cannot be the solution

**Comment by viktor44** [comment]
#203
