### ISSUE TITLE
Can't call with apps

### ISSUE THREAD

**Issue by abiggemann** [getstation/desktop-app#217]
Hi!

I was wondering if I've missing something as the options to call from Skype are blocked and on Whatsapp don't even appear.

Thank you in advance!

![SCR-20230927-laxq](https://github.com/getstation/desktop-app/assets/17080286/842660f7-ce22-42bd-bbbf-4610387fe2c6)
![SCR-20230927-lblc](https://github.com/getstation/desktop-app/assets/17080286/02a70e92-a8f8-4017-a16a-8cbcbd483f6c)

**Comment by viktor44** [comment]
Hi, 
web versions of those applications don't have such options. That's why they are invisible or disable

**Comment by abiggemann** [comment]
Oh! I wasn't aware! Thank you for the quick response 😃
