### ISSUE TITLE
Export unread messages from all messenger

### ISSUE THREAD

**Issue by Matlor** [getstation/desktop-app#220]
It would be amazing if I could get an overview over all my unread messages and export them to other productivity applications. Personally, I'd like to be able to create Notion tasks that remind me to text back on a specific messenger app after some amount of time not responding.

I don't completely follow how the codebase is structured to do this myself (don't have the time currently). 

Is there a way to run a script regularly that extracts the relevant data from the html of the pages?

**Comment by viktor44** [comment]
Hi @Matlor are you sure that it is a feature request for Station?
Looks more like secretary hiring ad
