### ISSUE TITLE
Connection to Microsoft Teams results in a blank screen

### ISSUE THREAD

**Issue by mikhailsirenko** [getstation/desktop-app#226]
Hi,

I've seen a number of issues reporting the same problem: Connection to Microsoft Teams results in a blank screen, but these were resolved by updating the Electron. However, for me, it didn't work. Can someone provide a guide on how to resolve this?

My OS is Windows 10 and downloaded the latest executable from the Releases page. The Station setup:

![image](https://github.com/getstation/desktop-app/assets/40139771/f2cd1198-4634-4b32-8e4f-b459954346a3)

**Comment by viktor44** [comment]
#80
