### ISSUE TITLE
Whatsapp location

### ISSUE THREAD

**Issue by GuyInAThong** [getstation/desktop-app#228]
I am trying to backup a bunch of stuff and free up space, wanted to get images out of whatsapp and can't find the location they go to when using station, if it still has a location folder to go to, like the normal whatsapp desktop.

Any help is appreciated, thank you for your time.

**Comment by viktor44** [comment]
What OS are you using?

**Comment by GuyInAThong** [comment]
Wrong email address

**Comment by GuyInAThong** [comment]
Wrong email address
