### ISSUE TITLE
ClickUp icon error

### ISSUE THREAD

**Issue by juanpebalsa** [getstation/desktop-app#237]
- Application version: _2.5.0_
 - OS: _Windows 11_

**Steps to Reproduce:**

1. Go to "+" and search ClickUp
2. See that the application icon does not appear.

**Screenshots**
![image](https://github.com/getstation/desktop-app/assets/33579495/0c547b37-9d53-4974-a8dc-79cf01667af3)

**Comment by viktor44** [comment]
the icon is PNG instead of SVG
