### ISSUE TITLE
Yarn run dev error

### ISSUE THREAD

**Issue by Lindsor** [getstation/desktop-app#241]
- Application version: Dev
 - OS: MacOS 14.0 M2

**Steps to Reproduce:**

git clone <repo>
yarn install
yarn run dev

A clean install / dev run of the application throws the bellow console error. The app does not even open instead just a floating chrome devtools window does with the content bellow.

**Screenshots**
<img width="787" alt="image" src="https://github.com/getstation/desktop-app/assets/3959304/73796d55-5621-4fc8-9146-42e85e010f1b">

**Comment by viktor44** [comment]
You have to change the architecture settings in `.npmrc` and run `yarn install` from scratch

```
arch = arm64
```

**Comment by Lindsor** [comment]
Thanks @viktor44  that worked.
I created PR here:
https://github.com/getstation/desktop-app/pull/244

I decided to remove the hardcoded architecture since it should no longer be needed. Its detected realtime by electron and dependencies.
I tested on clean `git clone` on M2 mac and it works.
If you rather ill update README instead

**Comment by viktor44** [comment]
Thank you @Lindsor
