### ISSUE TITLE
Problem with notification alerts

### ISSUE THREAD

**Issue by juanpebalsa** [getstation/desktop-app#242]
Application version: _2.5.0_
OS: Windows _11_

Steps to Reproduce:
Receive a notification from any application

Screenshots:
_For example, I receive a Slack message and get the windows notification,_ 
![image](https://github.com/getstation/desktop-app/assets/33579495/f59c7fd3-e763-43ed-8dd6-0863cb080932)
but it is not reflected anywhere in Station that there is a message.
![image](https://github.com/getstation/desktop-app/assets/33579495/a9cbd894-cc69-4c6e-a554-f57c182f2e96)
and also in the icon
![image](https://github.com/getstation/desktop-app/assets/33579495/d7483e5e-efbe-4962-84aa-6fb7d828b710)
But in slack there is nofication.
![image](https://github.com/getstation/desktop-app/assets/33579495/9066f117-fdd4-492d-b608-cf409d6c9dff)

Occurs with all applications

**Comment by viktor44** [comment]
#177
