### ISSUE TITLE
Open URL in default browser

### ISSUE THREAD

**Issue by mvaneijgen** [getstation/desktop-app#243]
Currently if you click a link it opens in a specific window. I would love it if you could set that it would open in your default browser.

**Comment by Lindsor** [comment]
@mvaneijgen  this is a duplicate of:
https://github.com/getstation/desktop-app/issues/178

Could you go like that issue please to get more traffic there.

Thanks

**Comment by mvaneijgen** [comment]
Tried finding similar topcis, but didn't find any. I'll follow that issue.
