### ISSUE TITLE
cannot select or click on anything in slack using station.

### ISSUE THREAD

**Issue by paragdesai1** [getstation/desktop-app#246]
- Application version: _[e.g. 2.2.1]_
 - OS: _[Windows 10, MacOS 13.4, CentOS 7 ...]_

**Steps to Reproduce:**

**Screenshots**

**Comment by viktor44** [comment]
Please add required details

**Comment by paragdesai1** [comment]
Application verson: 2.5.0
OS Mac 14.2
Open slack in station. Cannot click on any channels or chats from the left side in slack. 
Slick on search, allows to search but when clicking on a search item it does not work. 
Basically cannot navigate to any other chat, conversation, channels on slack. I can only chat in the one slack group that I used last before this issue started.
