### ISSUE TITLE
Slack not loading new messages automatically

### ISSUE THREAD

**Issue by geofferiswheel** [getstation/desktop-app#25]
Just downloaded the Station open source project.

Loaded my work slack account, that I used in the older version of Station. Never had a problem before today.

Slack app does not retrieve my new messages for me automatically. It continues to show a bubble with the message, "Last updated X minute(s) ago... Load new messages"

I continue to get notifications on my phone that I received a new message and then I have to manually "Load new messages" by clicking the link in the bubble. I've waited as long as 3 days to see if the messages would load on their own. I've checked my app settings, Slack notification settings, as well as removed the service and re-added. It's giving me the same behavior.

**Comment by ymoisan** [comment]
I started experiencing this issue today.  Slack on my Windows laptop notifies in real time but my Ubuntu client started asking me the "Load new messages" box today.  I checked notification settings on both clients and did no change in my Ubuntu client.

**Comment by AliceBreeveld** [comment]
I'm still having this issue. Has anyone found a solution?

**Comment by viktor44** [comment]
We have to check it in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)

**Comment by viktor44** [comment]
I'm closing it. 
We can reopen if there will be a new information
