### ISSUE TITLE
Add support for HTTP authentication

### ISSUE THREAD

**Issue by sitemapxml** [getstation/desktop-app#253]
I have some Munin monitoring instances that use digest HTTP auth, and I haven't found a way to add them to the Station browser.
It would be nice if this app could handle HTTP authentication.

**Comment by sitemapxml** [comment]
Hello @viktor44, you seem most active here, so I am mentioning you.
What do you think about this?

**Comment by viktor44** [comment]
It is a very rare auth method today. I don't know any site that use it.
I'm closing this issue now, but feel free to introduce the PR.
We will be happy to review it.
