### ISSUE TITLE
Cannot login to Protonmail using Station

### ISSUE THREAD

**Issue by thermopyle** [getstation/desktop-app#257]
- Application version: 2.5.0
 - OS: MacOS Sonoma 14.1.1
 
**Steps to Reproduce:**

1. Add Protonmail app in Station.
2. Type in user and password, hit Sign In.
3. An error message appears saying "The system has received too many requests recently. Please try again in a few moments.".
4. Using another browser to log in to Protonmail works fine, even after this error in Station.
5. Waiting 24h does not fix the problem.

**Screenshots**
<img width="1392" alt="Screenshot 2023-11-24 at 09 50 48" src="https://github.com/getstation/desktop-app/assets/1465241/a9cd0ad5-b979-4375-b3ee-0572800ab28b">

**Comment by viktor44** [comment]
Hi, just checked Proton Mail and it everything works prefect for me.
Anyway, I've updated URL. We used outdated URL for this site. Maybe it helps in your case.

**Comment by viktor44** [comment]
@thermopyle could you check if it's still an issue for 2.6.0?

**Comment by viktor44** [comment]
I'm closing it.
We can reopen if there will be a new information
