### ISSUE TITLE
Not able to use multiple WHatsapp accounts 

### ISSUE THREAD

**Issue by andrey2ksa** [getstation/desktop-app#259]
- Application version: 2.6.0
 - OS: Windows 11

**Steps to Reproduce:**

1. Go to Add apps and extensions
2. Add whatsapp
3. Setup whatsapp by connecting 1 whatsapp account 
4. Go to Add apps and extensions
5. Add another whatsapp
6. Try to setup a different whatsapp account ( different phone)

It does not allow you yo setup a different whatsapp account. It instead use the same whatsapp account previously setup

**Comment by viktor44** [comment]
That could be fixed with #131
