### ISSUE TITLE
Add ability to minimize to System Tray

### ISSUE THREAD

**Issue by andrey2ksa** [getstation/desktop-app#260]
Add the ability to minimize Station to the Windows system tray.

1. In the Options Form => General Category add a new On/Off toggle : "Minimize to System Tray"
2. When toggle is set to Off, Station minimizes to the Windows taskbar as it currently does
3. When toggle is set to On, Station minimizes to the Windows System Tray

Add a context menu to the Station System Tray icon containing these 2 options:
1. Open Staion - Open the Staion Main application 
2. Exit - CLose Station Application

Also add the ability to open the Station main application by double clicking over the Station System Tray icon.

**Comment by zj1123581321** [comment]
https://github.com/sandwichdoge/MinimizeToTray

I'm currently barely able to achieve this function through this program, hopefully it will be officially implemented soon, thanks : )

**Comment by papypom** [comment]
Yup, I'm gonna upvote this. Station is an excelllent piece of software, the ability to minimize to system tray would be the cherry on top.

**Comment by bouncer1798** [comment]
Yes please add this feature. This would make the app perfect.

**Comment by mabugaj** [comment]
I just updated to 3.3.0 and there's no such option in config and no tray icon. I'm using arch linux with kde (on wayland, maybe here is the problem, it's always wayland...).
