### ISSUE TITLE
Impossible to find any Extension

### ISSUE THREAD

**Issue by Seyukie** [getstation/desktop-app#269]
#### App Version:
Station version 2.6.0
Electron25.9.4
Chrome114.0.5735.289
Node18.15.0
v811.4.183.29-electron.0

---

#### OS:
Windows 10 Home 22H2

---

#### Steps to Reproduce:

I click on the plus (+) button "Add App & Extension", the Station App Center opens and then I click on "All Extensions", then it keeps searching forever without ever finding anything. 
(I do find Apps when I click on All Apps or when I search for them)

---

#### How I found it
At first I wanted to install the 1Password Extension for ease of use in the Station App, I do find the 1Password App when searching specifically for it, but not the Extension, it's after that, when trying to look for available extensions that I saw I couldn't find any

---

#### Screenshots
![Station App - Searching for extensions](https://github.com/getstation/desktop-app/assets/112772970/f080a090-c8e2-4d08-87bf-43fe15d73621)

**Comment by viktor44** [comment]
#195
