### ISSUE TITLE
QR Code - not showing

### ISSUE THREAD

**Issue by mariuzstoica** [getstation/desktop-app#27]
Hello, on macbook pro M1, QRcodes for login in to whatsapp, telegram not showing and cannot connect. the QR is only with loading icon.
![image](https://user-images.githubusercontent.com/89142181/129903065-e117cf88-979f-447d-9703-1f2f688bb12c.png)
![image](https://user-images.githubusercontent.com/89142181/129903100-6ae9b4d7-07f3-43e7-9faa-6216f39e222f.png)

**Comment by ikellenberger** [comment]
Might be related with #3
