### ISSUE TITLE
Unable to log into Gmail with Google Workspace account

### ISSUE THREAD

**Issue by ozdep** [getstation/desktop-app#270]
- Application version: 2.6.0
 - OS: Windows 10

**Steps to Reproduce:**

* Installed the latest version using the .exe file and replaced the user settings. 
* Added Gmail
* Attempted to add the account

**Screenshots**
![image](https://github.com/getstation/desktop-app/assets/17887252/fd19b178-4165-4427-800b-59ca355558fc)

**Comment by viktor44** [comment]
@ozdep We've made necessary settings. Could you please check if it works for you now?

**Comment by ozdep** [comment]
@viktor44 It works. Thank you!
