### ISSUE TITLE
Outlook sign-in does not handle the sign-in popup correctly

### ISSUE THREAD

**Issue by Davvos11** [getstation/desktop-app#274]
- Application version: 2.6.0
 - OS: Manjaro Linux
 
**Steps to Reproduce:**

1. Add a new Outlook app.
2. You will land on the Outlook homepage, which has two sign-in buttons, see screenshot 1.
Clicking button 2 (top-right) will take you to the sign-in page and will allow you to sign in with no problem.
3. Clicking button 1 (centre-left) will open a popup, which also allows you to sign in, see screenshot 2.
4. However, Outlook will now load in this popup, the main window will stay on the homepage of Outlook, see screenshot 3.
5. If you close the popup and press sign-in button 1, you will be taken to a page that shows you are signed out, see screenshot 4.

**Screenshots**
Screenshot 1:
![outlook_00](https://github.com/getstation/desktop-app/assets/20478740/aff93469-3b90-4294-86f6-0bd5d7afaf22)
Screenshot 2:
![outlook_01](https://github.com/getstation/desktop-app/assets/20478740/3bad2956-5113-45ea-bc6b-44dbbae31499)
Screenshot 3:
![outlook_02](https://github.com/getstation/desktop-app/assets/20478740/36eb7d0d-da31-432d-82f6-a466d346a574)
Screenshot 4:
![outlook_04](https://github.com/getstation/desktop-app/assets/20478740/9da5ddda-5226-4f80-95fd-161b290ffe97)

**Comment by viktor44** [comment]
@Davvos11 Thank you for detailed reports.
The issue you described should be fixed in the next release. 
It would be very helpful if you could check [pre-release 2.7.0-b1](https://github.com/getstation/desktop-app/releases/tag/v2.7.0-b1).
The bug have to be fixed there.
