### ISSUE TITLE
Ability to trust self-signed or expired certificates with private apps?

### ISSUE THREAD

**Issue by fanis** [getstation/desktop-app#278]
I have attempted adding a private URL app that runs on a local server with a self-signed TLS certificate. I'm getting error "-202:ERR_CERT_AUTHORITY_INVALID".

Is there a way around this by somehow adding an exception for this site?

**Comment by viktor44** [comment]
Probably https://github.com/getstation/desktop-app/issues/212 could help

**Comment by fanis** [comment]
The URL is not on localhost though. I tried anyway, doesn't work. Any other thoughts perhaps?
