### ISSUE TITLE
Unable to add google account

### ISSUE THREAD

**Issue by kkagitala** [getstation/desktop-app#28]
Tried to connect google account on the latest desktop app on Mac. I get the below error. 

![image](https://user-images.githubusercontent.com/56841735/129952177-b8ce6281-9037-4160-a47d-84b8a3750604.png)

**Comment by Tuba2** [comment]
Same issue reported in #2

**Comment by bgenchel** [comment]
Having the same issue

**Comment by les-larsj** [comment]
Having the same issue

**Comment by johanftg** [comment]
I have the same issue :(

**Comment by Collin-Nelson** [comment]
I'm having the same issue

**Comment by Jdunc30** [comment]
Having the same issue on Mac Big Sur

**Comment by kyletolle** [comment]
Also experiencing this on macOS Big Sur with Station version 2.0.9.

**Comment by kpinegar2** [comment]
Same issue here, is there any update?

**Comment by desmondfuller** [comment]
piling on.  Same thing.  Google Data Studio works however.

**Comment by ngonzalvez** [comment]
Seems to be related to [this](https://github.com/getstation/desktop-app/blob/9ed5d928aaed8e17153315273e9249f83e4a1c17/manifests/runtime/gdrive/main.ts#L16).

[This code](https://github.com/getstation/desktop-app/blob/9ed5d928aaed8e17153315273e9249f83e4a1c17/app/services/services/electron-google-oauth/main.ts#L7) is trying to get the CLIENT_ID variable from the environment. If you check the [.env.example](https://github.com/getstation/desktop-app/blob/9ed5d928aaed8e17153315273e9249f83e4a1c17/.env.example), the CLIENT_ID should be defined there. But if you check the [.env.production file](https://github.com/getstation/desktop-app/blob/9ed5d928aaed8e17153315273e9249f83e4a1c17/.env.production) it is never set.

Simple fix:
1. Clone the repo
2. Get custom OAUTH2 credentials for desktop apps [from here](https://console.cloud.google.com/apis/credentials)
3. Add the CLIENT_ID and CLIENT_SECRET variables to your .env file
4. Build the app

A more elegant solution would be to add a section in the app settings to set the CLIENT_ID and CLIENT_SECRET there.

**Comment by ngonzalvez** [comment]
BTW, in Windows, you can just add the credentials ot the `C:\Users\[USER]\AppData\Local\Programs\station-desktop-app\resources\.env.production` file instead of having to rebuild the app.

**Comment by johanftg** [comment]
How could  I do that? I’m only a programmer student hahah. I need more experience in that.But I will try to edit it in the Notepad Windows Program. Can you send me the correct form to write that in there?Thanks.De: Nicolás GonzálvezEnviado: Saturday, September 4, 2021 11:16 AMPara: getstation/desktop-appCC: pandaking; CommentAsunto: Re: [getstation/desktop-app] Unable to add google account (#28) BTW, in Windows, you can just add the credentials ot the C:\Users\[USER]\AppData\Local\Programs\station-desktop-app\resources\.env.production file instead of having to rebuild the app.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IgorBogdanovski** [comment]
Is there perhaps a little less "engineer-y" solution for this issue?

**Comment by leangseu** [comment]
For mac user you can edit file in `/Applications/Station.app/Contents/Resources/.env.production` then add `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`

**Comment by carsondarling** [comment]
@leangseu were you able to get this method to work? I've got a client ID and secret setup, but when I authorize an account, I first get redirected to the Station app, and then get redirected to https://getstation.com/app-login-success/#. 

It appears that it's related to https://github.com/getstation/desktop-app/blob/main/app/services/services/authentication/main.ts#L82, but I don't fully understand the actual authorization flow that Station is using.
