### ISSUE TITLE
All Extensions showing nothing

### ISSUE THREAD

**Issue by sfksuperman** [getstation/desktop-app#280]
When I try to open extensions, it shows nothing other than a rotating satellite animation.
<img width="646" alt="image" src="https://github.com/getstation/desktop-app/assets/34414624/ef13596a-b56b-4d4a-8d2c-28adb14e0ffa">

**Comment by sfksuperman** [comment]
<img width="646" alt="image" src="https://github.com/getstation/desktop-app/assets/34414624/670eeb53-4b98-4273-8399-22eb3f1ee4da">

**Comment by viktor44** [comment]
#195

**Comment by Simonsayszj** [comment]
same problem March 19 2024
