### ISSUE TITLE
Google Drive not allowed

### ISSUE THREAD

**Issue by sfksuperman** [getstation/desktop-app#282]
<img width="760" alt="image" src="https://github.com/getstation/desktop-app/assets/34414624/74a32972-0bfd-42cf-a6bf-8bbe813eebdb">

**Comment by viktor44** [comment]
For most of the cases Google Drive works fine.
Please provide more information.
Use [Bug report template](https://github.com/getstation/desktop-app/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=) if possible
