### ISSUE TITLE
Broken Icons

### ISSUE THREAD

**Issue by bert003** [getstation/desktop-app#286]
- Application version: _2.6.0_
 - OS: _Windows 10_

**Steps to Reproduce:**

1. Add an application to view the issue. Affected icons include:

- Pitchbook
- Aircall
- Calendly
- Outlook Calendar
- Scrapbox
- Google News
- Chromium Code Search
- CharlieHR
- HireSweet
- Payfit
- Recruitee
- ClickUp
- HubStaff
- Tinder

**Screenshots:**
Example of a broken icon shown below:
![image](https://github.com/getstation/desktop-app/assets/20399702/00eea383-95e5-4999-aaab-5dbf859ed213)

**Comment by viktor44** [comment]
Thank you for your report.
It's known issue. It will be fixed in 2.7.0

**Comment by viktor44** [comment]
#237
