### ISSUE TITLE
How to refresh the apps?

### ISSUE THREAD

**Issue by sfksuperman** [getstation/desktop-app#289]
Usually on official apps, we swipe-down to refresh the feed. How do we do it here?

**Comment by bert003** [comment]
Did you try pressing Ctrl+R?

**Comment by sfksuperman** [comment]
> Did you try pressing Ctrl+R?

Yeah, it's working that way. But don't you think there should be a "refresh" 🔃 button for this next to the "back" and "forward" arrows on the top left?
