### ISSUE TITLE
Cannot use with multiple google accounts

### ISSUE THREAD

**Issue by mkoo** [getstation/desktop-app#29]
Like others have mentioned, this has been my main app to handle multiple google accounts in mail, calendar and contacts. However, trying the workaround offered in this issue #2 with a customized app, I can only login to one google account at a time unlike the soon-to-be deprecated version.

Is there any update on whether the google authentication issues are prioritized or not?! I would hate to give up on an otherwise amazing tool!

**Comment by kpinegar2** [comment]
Same issue here, is there any update?
