### ISSUE TITLE
How do notifications work exactly?

### ISSUE THREAD

**Issue by bert003** [getstation/desktop-app#290]
Right now I never received a single notification in Station? And I am getting emails and messages regularly but the notification area remains as below:

![image](https://github.com/getstation/desktop-app/assets/20399702/8f87b82a-0be5-4022-9132-77044fb62a93)

Do not disturb mode is off as well. Maybe I am missing something?

**Comment by viktor44** [comment]
The issue #177 is still waiting for a volunteer 😄
