### ISSUE TITLE
Screen sharing on Slack doesn't seem to work

### ISSUE THREAD

**Issue by mythmon** [getstation/desktop-app#293]
- Application version: _2.7.0-b1_
 - OS: _Arch Linux_

**Steps to Reproduce:**

1. Go to a Slack instances
2. Start a huddle
3. Try to share screen
4. The icon activates, but no screen share or prompt happens.

**Screenshots**

![image](https://github.com/getstation/desktop-app/assets/305049/fdb28eed-b734-4184-87e0-362782b27c79)

**Comment by viktor44** [comment]
seems to be the same #95

**Comment by ericgoetz** [comment]
I've never been able to get it to work, either. I always assumed it was my fault and that it had to do with some arcane MacOS security model setting (I'm running Sonoma 14.1.2). Useful to know that it's happening for LInux, as well.

**Comment by viktor44** [comment]
https://github.com/getstation/desktop-app/issues/95
