### ISSUE TITLE
Profile (and Apps ) sync across multiple machines

### ISSUE THREAD

**Issue by gionaguidi** [getstation/desktop-app#294]
I would love to be able to use google, or any other method, to sync my Station set up and Apps across multiple Mac machines

**Comment by viktor44** [comment]
What exactly do you want to sync? 
We can't sync auth information so have to authorise yourself on a new place . 
Installed applications? It is possible, but TBH I don't see the value in this feature.

**Comment by gionaguidi** [comment]
> What exactly do you want to sync? We can't sync auth information so have to authorise yourself on a new place . Installed applications? It is possible, but TBH I don't see the value in this feature.
> 
> Anyways, feel free to implement it. We will be happy to review the PR

Well, i think that users using multiple machines would benefit from having all the apps set up the same way automatically on each Mac. Same apps, same disposition, same settings.
