### ISSUE TITLE
Screen sharing doesn't work with Teams and Telegram

### ISSUE THREAD

**Issue by AutumnWohlen** [getstation/desktop-app#300]
- Application version: 2.6.0
 - OS: Windows 10, Windows 11

I don't think that it is a certainly a bug. If you use electron with chromium, you just need to add an option to edit permissions for the application. In Chrome it looks like this:
chrome://flags/
chrome://flags/#enable-webrtc-pipewire-capturer = Enabled

**Comment by viktor44** [comment]
It's not so easy. Sorry

**Comment by viktor44** [comment]
#293

**Comment by AutumnWohlen** [comment]
Ok, how about this:

Ensure that your BrowserWindow in Electron has WebRTC enabled. This can be done by setting the "webPreferences" option when creating a new BrowserWindow:

`const { app, BrowserWindow } = require('electron');

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      webSecurity: false, // This might be necessary for accessing screen-sharing APIs
      enableRemoteModule: true, // If using Electron 14 or later
    },
  });

  // Load your application URL
  mainWindow.loadURL('your_application_url');
});
`

**Comment by tubido-tech** [comment]
@AutumnWohlen you are welcomed to introduce the PR
