### ISSUE TITLE
Open Links from Outlook in Browser!

### ISSUE THREAD

**Issue by LRrebekka** [getstation/desktop-app#303]
- Application version: 2.6.0
Electron25.9.4
Chrome114.0.5735.289
Node18.15.0
v811.4.183.29-electron.0

 - OS: MacOS 14.2.1 

**Steps to Reproduce:**

1. Go to Outlook
2. Click on any link in e-mail
3. Link is opened in a small window of station app instead of browser - and user is not asked for „open in browser instead“

**Screenshots**
![Bildschirmfoto 2024-01-05 um 11 27 28](https://github.com/getstation/desktop-app/assets/91665338/4f393844-10ab-461a-958c-4e44ff7f5a95)

**Comment by viktor44** [comment]
Use `Cmd+Click` or `Shift+Click`
