### ISSUE TITLE
Failing to log in to Notion (Ubuntu 22.04)

### ISSUE THREAD

**Issue by ronentk** [getstation/desktop-app#307]
- Application version: _[e.g. 2.6.0]_
 - OS: _[Ubuntu 22.04]_

**Steps to Reproduce:**

1. Go to 'Add apps and extensions'
2. Click on 'Notion'
3. Click on 'Continue with Google'
4. See error below

Notes:
- After step 3 the browser would open on the following URL https://www.notion.so/verifyNoPopupBlockerHtmlAndRedirect?redirectUri=https%3A%2F%2Fwww.notion.so%2Fgooglepopupredirect%3FcallbackType%3Dpopup%26redirectToAuth%3Dtrue and then it would close rapidly (except on Firefox where that tab stayed open), followed by error described in step 4
- I tried changing my default browser to Chrome, Brave and Firefox, and in each I tried enabling pop-ups

**Screenshots**
![image](https://github.com/getstation/desktop-app/assets/1759025/c84b9207-b56c-496f-819c-fa42f16021fe)

**Comment by viktor44** [comment]
Fixed in [2.7.0](https://github.com/getstation/desktop-app/releases/tag/v2.7.0)

**Comment by sulabula77** [comment]
I have an EHR I use through Station, and trying to open up a document from within a chart.  It worked perfectly when I used Shift, but in Station, it says I need to allow pop ups.  Except all the settings are in place to allow them.  I'm on a MacBook, and have no idea how to fix this.
