### ISSUE TITLE
Changed code signature in MacOS version 2.7.0

### ISSUE THREAD

**Issue by suschizu** [getstation/desktop-app#308]
hello @viktor44 - I've noticed that the code signature has changed in version 2.7.0 - can you confirm it? thanks

EXPECTED 'Joel Charles (5D95778L6J)' 
FOUND 'Viktor Kadachigov (6ZT9HVU37U)'

- Application version: 2.7.0
 - OS: MacOS 13.6

**Steps to Reproduce:**

codesign -dv --verbose=4 /Path/To/Application.app

<img width="823" alt="Screenshot 2024-01-15 at 20 45 00" src="https://github.com/getstation/desktop-app/assets/16004333/2a740fd7-66cb-4bda-ac68-c85137e157a0">

**Comment by viktor44** [comment]
Yes. We had to do it.
I added the comment about it to the release notes

**Comment by suschizu** [comment]
oh, sorry for not looking closer to the release notes
