### ISSUE TITLE
Mac "about" dialog doesn't have control buttons

### ISSUE THREAD

**Issue by libroraptor** [getstation/desktop-app#309]
- Application version: 2.7.0
 - OS: MacOS 11.7.10

The red, yellow and green (close, minimise size, maximise) control buttons are white and inactive on the About dialog. There is no indication of how to close the window (but pressing escape does it).

**Steps to Reproduce:**

1. Menu item Station > About 

**Screenshots**
<img width="662" alt="image" src="https://github.com/getstation/desktop-app/assets/130518279/7249b3a7-602e-4d05-b39b-21517d94d3d8">

Top left corner should look like this: 
<img width="111" alt="image" src="https://github.com/getstation/desktop-app/assets/130518279/5ad89977-6e5e-4611-ad90-5937b82526e8">

**Comment by viktor44** [comment]
it was designed like this

**Comment by libroraptor** [comment]
The red button should be enabled. The yellow and green are not needed for an About window, but it's a fundamental of UI that the red button not be disabled here.
