### ISSUE TITLE
Facebook Messenger "No Internet Warning" - Unable to Search and Find Users - Chat doesn't work.

### ISSUE THREAD

**Issue by bgenchel** [getstation/desktop-app#31]
Facebook messenger app seems very faulty. It constantly shows "No Internet" then "Connecting to Internet" in red lettering at the top of the chat window. 

I was also unable to search for a chat with a friend. The friend showed up upon searching their name, but after clicking on their name, the chat didn't show up. I just see an empty pane with a blank "Facebook User" at the top.

**Comment by jamilnyc** [comment]
I have the same issue. When using Messenger in Station, I usually see `No internet connection` at the top. I'm able to use Messenger in Safari, so my internet connectivity is not an issue.

**Comment by viktor44** [comment]
#143
