### ISSUE TITLE
Google signin no longer works since 2.7.0 on Mac

### ISSUE THREAD

**Issue by libroraptor** [getstation/desktop-app#311]
- Application version: 2.7.0
 - OS: MacOS 11.7.10

**Steps to Reproduce:**

Google signin fails on Android Messages and Twist. (Yet can still sign in on Google Keep, Google Chat.)

Attempting to log in leads to the rejection screen below:

**Screenshots**
<img width="472" alt="image" src="https://github.com/getstation/desktop-app/assets/130518279/4cdc428e-ebcd-47d8-813a-f8f7190d3e1c">

**Comment by zj1123581321** [comment]
I'm having the same problem.

Learn more  link：https://support.google.com/accounts/answer/7675428

**Comment by gt-fm-4562** [comment]
Having same issue since 2.7.0

**Comment by viktor44** [comment]
Fixed in [2.7.1](https://github.com/getstation/desktop-app/releases/tag/v2.7.1)

**Comment by libroraptor** [comment]
I confirm that it's working now.
