### ISSUE TITLE
I cannot log in to Google Chat (Workspace)

### ISSUE THREAD

**Issue by Nyanco-Kotohomu** [getstation/desktop-app#319]
I reached the login screen of Google Chat and entered my ID/Password, but after a while I get an error like the attached image. 
It happens every time. I tried to use a custom app and enter [https://chat.google.com/] directly, but I get a message saying [Your current browser is not compatible with Google Chat.]. 
Is there something wrong?

![image](https://github.com/getstation/desktop-app/assets/46469258/d84a3a0b-f1cf-4dc4-8044-4e2430beda7c)

**Comment by jthadden** [comment]
Same here with hangouts/gchat. In our company we have an own authenticator enabled for that. It opens, I can enter my credentials and get forwarded to the chat, where I get an annoying "Your current browser is not compatible with Google Chat." Was working with 2.7.0 and a custom app, only. Broke with 2.7.1 or 2.7.2 in the normal and the custom app.
