### ISSUE TITLE
Unable to login to GMail

### ISSUE THREAD

**Issue by mjasyal-z** [getstation/desktop-app#32]
I am trying to login to my Google work account.
I get this OAuth error:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/46006239/130640098-6202cfdf-4c3a-4507-8ccc-623887dd09f0.png">

The authentication works fine on a regular browser.

**Comment by matbgn** [comment]
+1

**Comment by kpinegar2** [comment]
Same issue here, is there any update?

**Comment by mjasyal-z** [comment]
> I am trying to login to my Google work account.
> I get this OAuth error:
> 
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/46006239/130640098-6202cfdf-4c3a-4507-8ccc-623887dd09f0.png">
> 
> The authentication works fine on a regular browser.

I found a workaround. For whatever reason, Google Hangout works fine. Sign in to that first, and then use the app menu on the top left of the hangout window to jump to other applications.

**Comment by kpinegar2** [comment]
> I can confirm that the work around used by @mjasyal-z works . It appears that the login for hangouts occurs in the station application where as the login for gmail, calendar, and drive all open up the default web browser for login.

It works, but only if you use 1 single gmail account (unless others have managed to make it work with multiple).

**Comment by Lr-2002** [comment]
Hi guys,I followed @kpinegar2 's suggestion, but it show me : the broswer is not safe ..
any suggestion ?

**Comment by Lr-2002** [comment]
well ,i'm from china using proxy

**Comment by Lr-2002** [comment]
all right,problem settled with long time trying and fresh

**Comment by convertl** [comment]
I get the same error trying to connect to Hangout : "This browser is not safe". Any clue to get Gmail/GDrive account working on Station ?

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
