### ISSUE TITLE
Open link in the browser by default

### ISSUE THREAD

**Issue by cgonzalezsan** [getstation/desktop-app#322]
- Application version: 

Stationversion 2.3.0
Electron24.4.0
Chrome112.0.5615.204
Node18.14.0
v811.2.214.22-electron.0

Right now I have to right click and select open in browser, otherwise it'll open a new station window. It'd be nice to be able to do this directly by clicking on it.

**Comment by viktor44** [comment]
You can use Cmd+Click or Shift+Click to open link in browser

**Comment by viktor44** [comment]
#178
