### ISSUE TITLE
Downloaded files are always hidden on Mac

### ISSUE THREAD

**Issue by cgonzalezsan** [getstation/desktop-app#323]
- Application version: 

Stationversion 2.3.0
Electron24.4.0
Chrome112.0.5615.204
Node18.14.0
v811.2.214.22-electron.0

 - OS: _MacOS 14.2.1 (23C71)

**Steps to Reproduce:**

1. Go to whatsapp
2. Download a file from your contacts
3. The file will be hidden

**Screenshots**

**Comment by viktor44** [comment]
> The file will be hidden

What exactly do you mean saying it?

I would also recommend you to [update Station](https://github.com/getstation/desktop-app/releases/tag/v2.7.3)

**Comment by viktor44** [comment]
Closing it due to inactivity
