### ISSUE TITLE
Run Station with parameters

### ISSUE THREAD

**Issue by dan83g** [getstation/desktop-app#325]
For some automation I need to run a station with parameters.
For example: `station -url http://example.com?q=123`
If the station is already running, it should not open a new instance, it should open URL in a running instance.
Thanks in advance.

**Comment by viktor44** [comment]
What do you want to achieve with it?
It's now a browser. URL is not enough to add new custom app.
Please elaborate your idea

**Comment by viktor44** [comment]
Closing it due to inactivity
