### ISSUE TITLE
App Teams - Randomly logged out

### ISSUE THREAD

**Issue by rzr8891** [getstation/desktop-app#326]
- Application version: 2.7.3
 - OS: Windows 10 Pro

**Steps to Reproduce:**

1. Go to Teams app
2. Find the App frozen (white screen)
3. Reload or wait a few minutes
4. App refreshes back to login screen
5. Input the login details correctly
6. Microsoft account is not recognized 

The only solution is to delete instance and add again. Afterwards using the same credentials I log in with no issue.

This happens a few times a week.

**Comment by viktor44** [comment]
1. Go to Teams app
 2. Find the App frozen (white screen)

Can't reproduce step 2. Application opens without problems
We need more details to fix it.

**Comment by rzr8891** [comment]
It seems to be fixed in the latest version.
