### ISSUE TITLE
For everyone having issues with QR codes or Gmail or logging-in... Read Me

### ISSUE THREAD

**Issue by technowhizz** [getstation/desktop-app#33]
Check out [Ferdi](https://getferdi.com). Sure it doesn't have extensions (yet?) but it works really well. It is slightly different in that it doesn't do the grouping that getstation does but it's still a really good all-in-one messaging app.

**Comment by Salimzz** [comment]
@technowhizz did you find any solution for discord etc ?

**Comment by technowhizz** [comment]
@Salimzz I moved over to ferdi :)

You should deffo try it https://getferdi.com/

**Comment by Salimzz** [comment]
Is it a paid app ? :)

**Comment by technowhizz** [comment]
It's open source :)
