### ISSUE TITLE
Station App Stuck At Launch

### ISSUE THREAD

**Issue by MrNDeYoung** [getstation/desktop-app#330]
- Application version: _[2.6.0]_
 - OS: _[MacOS 14.2.1.]_

**Steps to Reproduce:**

Frequently when I restart my Mac and launch station, I see the screen below indefinitely. The only fix I've found is a combination of restarting/shutting down and hoping it works when I log back in.

Any idea what is wrong or a better solution to fix?

(P.S. -  This is my first time submitting a Github request so I hope I'm doing it correctly.)

**Screenshots**

![Screenshot 2024-02-08 at 1 31 11 PM](https://github.com/getstation/desktop-app/assets/159482930/1d705e1a-5884-4251-a48a-90b4c9eeb428)

**Comment by viktor44** [comment]
Please try this https://github.com/getstation/desktop-app/issues/203#issuecomment-1717353312
Does the workaround work for you?

**Comment by MrNDeYoung** [comment]
Yes that seems to work, thank you so much!

**Comment by viktor44** [comment]
#203

**Comment by joefirstme** [comment]
still on station 3.3.0 and sonoma 14....
