### ISSUE TITLE
Cannot use any of Google extensions

### ISSUE THREAD

**Issue by maxmetalm** [getstation/desktop-app#335]
- Application version:  2.7.0-b2, 2.7.3
- OS: linux mint  21.3

**Steps to Reproduce:**
1. add any google extension
2. click 'Add a new account'
new tab in the main browser is opened, not inside the Station (I suppose here is an issue)
3. Sign in there
Access blocked: Authorization Error
Missing required parameter: client_id
Error 400: invalid_request

**Comment by viktor44** [comment]
I suppose you are trying to built it from sources
In this case you have to setup the environment.

```
GOOGLE_CLIENT_ID=yyyy
GOOGLE_CLIENT_SECRET=xxxx
```

or you can download release here
