### ISSUE TITLE
I can't see the slack icon on the Mac version.

### ISSUE THREAD

**Issue by takuto0515** [getstation/desktop-app#34]
Hello.

I'm using the latest version (2.0.9) for Mac, and I've activated "DOCK ICON" in the slack app settings, but the slack team logo is not showing up.

I've joined 10 of these teams and the logo is not showing for all of them.

I've tried rebooting but no luck. Is there any solution?

Also, as others have said, when I try to log into the Google app, I get an authentication error.

**Comment by jsavin** [comment]
This used to happen to me on 1.6.x before Station was open-sourced. The workaround I used was to open a page like the Customize Slack page for each Slack instance and it would trigger the team icon to load. At some point that stopped working.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
