### ISSUE TITLE
Discord Stuck on Loading Screen

### ISSUE THREAD

**Issue by KyngW** [getstation/desktop-app#35]
I have been using an older version for a while. I made the mistake to update and now discord would not let me log in. Just the icon looping endlessly. Is there an easy fix?

**Comment by rumhamsec** [comment]
> 
> 
> I have been using an older version for a while. I made the mistake to update and now discord would not let me log in. Just the icon looping endlessly. Is there an easy fix?

I am also experiencing this. Along with slack not updating messages properly. Did you ever find a fix @KyngW ?

**Comment by KyngW** [comment]
@rumhamsec I followed what is mentioned in issue #33. Worked like a charm, even smoother running.
