### ISSUE TITLE
Notification Counter on the app icons

### ISSUE THREAD

**Issue by Anirban12a** [getstation/desktop-app#356]
I hope this message finds you well. I've been an avid user of Station and find it incredibly useful. However, I haven't been able to find an option to enable a notification counter on the app icon. If such an option exists and I've overlooked it, could you please guide me?

Additionally, I believe implementing a notification counter feature would greatly enhance user experience by providing quick access to pending notifications. It's a small addition that could make a big difference.

Thank you for considering my suggestion.

**Comment by viktor44** [comment]
Depends on #177

**Comment by viktor44** [comment]
#299
