### ISSUE TITLE
Non Yarn way to install this software

### ISSUE THREAD

**Issue by Xpistos** [getstation/desktop-app#36]
Is there a non-yarn way to install this software. I spent about 3 hours trying to get this installed because the app store doesn't work and the login goes to a bad url.

I have about had it with new frameworks people. Pick one and stay with it.

**Comment by macdabby** [comment]
I had the same issue but i was able to get it to run with the appimage on linux. just download, change to executable and open it. there is also an exe and dmg which i would image work just as easy for windows and mac: https://github.com/getstation/desktop-app/releases/tag/v2.0.9

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
