### ISSUE TITLE
Slack workspace not loading within the Station App

### ISSUE THREAD

**Issue by aldrichtan** [getstation/desktop-app#372]
- Application version: 2.73
 - OS: MacOS Monterey V12

**Steps to Reproduce:**

1. Sign in to a slack workspace
2. Complete sign up
3. See workspace menu
4. Click on a workspace to Open
5. Station opens a new window for the workspace (i don't want this! the old version of station used to open the workspace within the Station app window)
6. No idea how to bring it into the same window 

<img width="1253" alt="Screen Shot 2024-05-08 at 11 22 59 AM" src="https://github.com/getstation/desktop-app/assets/65532574/df6d3a3b-3c5e-46b2-9ecf-5bede1f67a9d">

**Comment by viktor44** [comment]
Hi, can't reproduce.
I don't understand "3. See workspace menu"
After login I see

![image](https://github.com/getstation/desktop-app/assets/8362098/cdc7301d-8275-43f4-850d-a0e1bc111df0)

What did I miss?

**Comment by aldrichtan** [comment]
hey @viktor44 ! 

What I mean by #3 is if your Slack email is tied to multiple workspaces, you can pick which one you want to launch. 

The view within my station app shows a list of workspaces to choose from, and when I click them, it just opens up a new Station window with the slack environment. But I cannot get it back into the main app window.

Currently, it is also stuck in a slack loading screen. This is also on a Mac... Not sure if this is a local machine error or a Slack thing itself where it limits 3rd party clients? 


<img width="1157" alt="Screen Shot 2024-05-13 at 12 42 53 PM" src="https://github.com/getstation/desktop-app/assets/65532574/0ffe31bd-d9fe-46f2-9bd5-f21993d3a8c1">

**Comment by viktor44** [comment]
Still can't reproduce the issue.
Now I have 2 workspaces for my user
![image](https://github.com/getstation/desktop-app/assets/8362098/4af0056d-a358-4fa6-9d52-a0d99629ca27)

but there is no selection on start. 
we select the workspace at the first page http://workspace-name.slack.com right?

**Comment by viktor44** [comment]
Closed due to innactivity

**Comment by dagomar** [comment]
@aldrichtan I had exactly the same issue, but I think I know what is happening. I had added a slack 'team' as it's called for my enterprise, like so: name-of-corp.enterprise.slack.com.
That gave me the same page as you, with options to open workspaces; Each workspace is in fact it's own full blown Slack instance, with its own URL. When clicking those, they opened in new windows for me as well. You need to use the dedicated workspace URL to Station. 
You can see the URL when you click on the workspace (not the launch button for it).
