### ISSUE TITLE
JavaScript support - unable to load Gmail

### ISSUE THREAD

**Issue by monikeraudio** [getstation/desktop-app#373]
Has Station just dropped out of support with a Gmail change? Currently can't access Gmail via Station with no changes on my end. 

<img width="488" alt="Screen Shot 2024-05-08 at 3 23 37 pm" src="https://github.com/getstation/desktop-app/assets/98502742/0675075d-426c-488b-886f-1413a2b67748">

**Comment by monikeraudio** [comment]
deleted account and re-added...back to normal

**Comment by viktor44** [comment]
I'm closing it then.
