### ISSUE TITLE
Install instructions for Mac

### ISSUE THREAD

**Issue by clickbrain** [getstation/desktop-app#378]
Havign a heck of a time finding instructions for installing Station on Mac. It doesn't look like you guys provide actual app files for this app.

**Comment by viktor44** [comment]
_**MacOS**: I can't create DMG distribution now. Use [Station.zip](https://github.com/getstation/desktop-app/releases/download/v3.0.0/Station.zip). Unpack it to `Applications` folder._ 

Thank you for your question. I've updated release description.
