### ISSUE TITLE
Cannot click "connect" button on Brave Browser

### ISSUE THREAD

**Issue by IgorBatchev** [getstation/desktop-app#38]
Hello, few days ago Station prompted me to login again, but now the "connect" button doesn't do anything. It reacts when I click but no prompt opens.
I'm using Brave Version 1.28.106 Chromium: 92.0.4515.159 (Build officiel) (64 bits)

**Comment by paytifix** [comment]
I have had same problem. May be reason is our location, russian internet)). I can't reach https://getstation.com/ without VPN
