### ISSUE TITLE
Browser version soon to be out of date for Slack app (September 1, 2024)

### ISSUE THREAD

**Issue by Rodhlann** [getstation/desktop-app#380]
- Application version: 3.0.0
 - OS: MacOS 14.5

**Steps to Reproduce:**

1. Go to Slack space on sidebar
2. Click on Add a new Team
4. See banner "This browser won’t be supported starting September 1st, 2024. Update your browser to keep using Slack. [Learn more](https://slack.com/help/articles/1500001836081)"

Note: I am not certain what browser Station is using in the background, but I have seen this banner several times and am hopeful that it can be resolved before September! 

**Screenshots**
<img width="1678" alt="image" src="https://github.com/getstation/desktop-app/assets/14314575/de5dfcdc-11db-4711-a696-9a9533a73674">

**Comment by viktor44** [comment]
Just close this message
We will update browser version as soon as we have a capacity.
