### ISSUE TITLE
Add support for wayland

### ISSUE THREAD

**Issue by Theblackcat98** [getstation/desktop-app#381]
- Application version: _[3.0.0]_
 - OS: _[Fedora 39]_

Bug Report/Feature Request: In general with most application packaged as flatpaks, I can usually add flags to open apps using Wayland/Xwayland; but with ".appimages" it isn't possible.
Using the app while in the Wayland environment causes flickering and graphical issues.

**Steps to Reproduce:**

1. Open the Station app via ".appimage"
2. Click on any UI button that causes the screen to be refreshed
3. Flickering and UI disappears off and on

**Screenshots**

**Comment by viktor44** [comment]
Are you talking about `--enable-features=UseOzonePlatform --ozone-platform=wayland` parameters?
By the way it works without flickering in CentOS 9. Is it depends on hardware?

**Comment by viktor44** [comment]
@Theblackcat98 any comments on the topic?

**Comment by Theblackcat98** [comment]
My apologies, didn't see you replied. 
And yes I am talking about those parameters as an example of what I would do if it was a flatpak.
I do know that Wayland has had issues with Nvidia (but also many other projects) for a while now. Therefore, in a way it is dependent on hardware.
Although I've gotten other applications to work with my setup.
Please let me know what more information I can provide to help you :)

**Comment by Theblackcat98** [comment]
P.s. GitHub Mobile is strange, I just saw the updated code block. Thank you! 
I will update the app and report back on Monday

**Comment by viktor44** [comment]
Please check this release https://github.com/getstation/desktop-app/releases/tag/v3.1.0-b2

**Comment by viktor44** [comment]
@Theblackcat98 could you confirm that the fix works for you?
