### ISSUE TITLE
Support quitting the application with Ctrl+Q on Linux

### ISSUE THREAD

**Issue by jfpedroza** [getstation/desktop-app#383]
What the title says. I think quitting with Ctrl+Q on Linux is way more common than with Alt+F4.

**Comment by viktor44** [comment]
I've checked Debian and CentOS. Alt+F4 works in both for all applications
TBH I don't think it's something we should change.

**Comment by jfpedroza** [comment]
I wasn't suggesting removing the Alt+F4 shortcut, just add another shortcut. I use a 60% keyboard with no dedicated F keys, so I'm used to quitting with Ctrl+Q that requires fewer keystrokes.
