### ISSUE TITLE
Screen sharing doesn't work in Teams

### ISSUE THREAD

**Issue by fpasqua75** [getstation/desktop-app#384]
I can't share the screen in Teams meetings.

- Application version: 

    - Stationversion 3.0.0 (AppImage)
    - Electron27.3.11
    - Chrome118.0.5993.159
    - Node18.17.1
    - v811.8.172.18-electron.0

 - OS: Fedora 40

**Steps to Reproduce:**

1. In a meeting, click the Icon to share the screen
2. Click on "Screen, window..." ("Schermata, finestra o scheda" in italian)
3. See error

"Video not working" (I see it in italian: "Il video non funziona")
"Impossible to access to webcam" ("Impossibile accedere alla fotocamera")

**Screenshots**
![immagine](https://github.com/getstation/desktop-app/assets/131980131/6b070722-5aec-4b7f-a263-417d88411b68)

PS: I tried also with skype, clicking on the screen share icon has no effect, but there is no error.

**Comment by viktor44** [comment]
#95
