### ISSUE TITLE
YouTrack application wrongly assumes usage of cloud version

### ISSUE THREAD

**Issue by tiritto** [getstation/desktop-app#386]
- Application version: 3.0.0
- OS: Windows 11 Pro

**Steps to Reproduce:**

1. Go to 'Add apps and extensions'
2. Add 'YouTrack'
3. You're being forced to enter a subdomain under '.myjetbrains.com' domain, even though YouTrack can be self-hosted under your independent domain.

**Screenshots**
![image](https://github.com/getstation/desktop-app/assets/5196829/a04cfc20-480f-4d85-816e-604fbaed212e)

**Comment by viktor44** [comment]
Try https://github.com/getstation/desktop-app/releases/tag/v3.1.0-b1
