### ISSUE TITLE
Asana producing 504 Gateway Time-out Error within the Station App

### ISSUE THREAD

**Issue by bednarz5** [getstation/desktop-app#389]
- Application version: 3.3.0
 - OS: Windows 10

**Steps to Reproduce:**

**Attempt 1:**
1. Sign-in to a Asana (for both google sign-in and email sign-in it works initially for the first instance, but if I try to add another email 
2. Click on account drop-down menu in the top right corner.
3. Click on settings
4. Select Account 
5. Click "add new email" - forces you to reauthenticate
6. Select same email again
7. 504 Gateway Time-out error appears

**Attempt 2:** 
1. Select Asana app
2. 504 Gateway Time-out error appears
3. Quit and restart Station
4. Sign-in to Asana with email - takes you to sign-up page (but I already have an account with that email so...)
5. Select "log-in" (located on bottom of page)
6. 504 Gateway Time-out error appears

**Attempt 3:**
1. Select Asana app
2. 504 Gateway Time-out error appears
3.  Select "Help"
4.  Select "reset current application"

**Attempt 3.1:** 
Repeat of Attempt 1 OR
Repeat of Attempt 2 Steps 1-3 and then 504 Gateway Time-out error appears again

**Screenshots**
![image](https://github.com/getstation/desktop-app/assets/114885060/83615d6b-7ac1-4ddc-b5e4-122c7edde6f1)

**Comment by viktor44** [comment]
Hi @bednarz5 , I would recommend you to add another Asana app to Station and login with a different account instead of adding second account to the single Asana app.
Like this:
![image](https://github.com/getstation/desktop-app/assets/8362098/440dc1e0-bd21-43b9-9a3c-ba584aa8fe52)
