### ISSUE TITLE
Icon Images not loading on MacOS

### ISSUE THREAD

**Issue by dshark3y** [getstation/desktop-app#39]
Hi, See the image below. Ive tried reinstalling, cleaning out the folder as per the FAQ, and with/without VPN/custom DNS.

Any advice? Everything works, its just visually painful

<img width="317" alt="Screen Shot 2021-09-06 at 02 42 48" src="https://user-images.githubusercontent.com/19961868/132143534-93b7a777-a3ed-45bb-8753-4df06f335020.png">

**Comment by iefuji** [comment]
![image](https://user-images.githubusercontent.com/48354582/138228002-faa54a6f-d29f-4311-a207-7e1bdac80f99.png)
It will be the same on Windows 10
