### ISSUE TITLE
Can you put the message reminder on the left icon? I have many accounts logged in, so I won’t miss my messages. Thank you

### ISSUE THREAD

**Issue by Abe778884** [getstation/desktop-app#391]
![5ce2a4ee-3051-4521-aa73-be146acc44ac](https://github.com/getstation/desktop-app/assets/174059362/f936bfb8-91dd-480d-a6cc-83c8e0cb1804)
Can you put the message reminder on the left icon? I have many accounts logged in, so I won’t miss my messages. Thank you

**Comment by viktor44** [comment]
#177
