### ISSUE TITLE
Pop-up Windows Don't go Back and Forth in Pages

### ISSUE THREAD

**Issue by CookieUndercover1212** [getstation/desktop-app#394]
- Application version:  3.0.0
 - OS: Windows 10

**Steps to Reproduce:**

1. Go to any website with links in them (e.g. an email with a link to a website)
2. Click on link to open in a new window (e.g. clicking on the link, which automatically opens the site in a new window)
3. Click on any link within the window, as long as it doesn't create another pop-up window.
4. Try pressing Ctrl[and Ctrl] to go back and forth between pages; realize that doesn't work.

I've also noticed that there aren't back and forth arrows in the pop-up windows. I think this feature should be added.

**Comment by viktor44** [comment]
#185
