### ISSUE TITLE
I can't login to google and get an error message.

### ISSUE THREAD

**Issue by k-akihiro1** [getstation/desktop-app#40]
The contents of the error message are as follows.
How can I do this?

Authorization Error
Error 400: invalid_request
Missing required parameter: client_id

**Comment by lizzydh** [comment]
Same here - Mac version.

**Comment by rasmus2000** [comment]
Same 😥 - Windows 10

**Comment by vdrover** [comment]
Same

**Comment by kajikuni** [comment]
Same Mac/2.0.9

**Comment by sbbeebe** [comment]
Same - new user evaluating and unfortunately, I can't set up my Google Workspace account. Although, funny thing. I was able to set up Google Chat using my GW credentials. But everything else fails - Mail, Drive, Calendar...

MacOS 11.5.2 / Station 2.0.9

**Comment by Jordanddub** [comment]
Same, there was a "learn more'" link that directed me here:
https://developers.google.com/identity/protocols/oauth2

Problem with Oauth?

Anybody have a workaround? I'm a noob dev.

**Comment by ysko909** [comment]
Same.

MacOS Big Sur 11.5.2 Station 2.0.9

**Comment by BaderSerhan** [comment]
Same. Is there any fix soon?

**Comment by mryusufcan** [comment]
what is the solution? please help

**Comment by aaddi19** [comment]
same :(

**Comment by devguilhermy** [comment]
Same problem here, can't log to any google service. Please fix soon

**Comment by revoiot** [comment]
google系のアプリが連携できなくなっています。

**Comment by revoiot** [comment]
I decided to change my app to Biscuit. Thank you so far!!
https://eatbiscuit.com/
