### ISSUE TITLE
Teams password error

### ISSUE THREAD

**Issue by mattinvietnam** [getstation/desktop-app#409]
Application Name : Station
OS: Mac OS Sonoma/Ubuntu 24.04
Application version: 2.6 on Mac/3.1 on Ubuntu

I use Station on two machines - Mac OS Sonoma and Ubuntu 24.04  and have had the same issue with both.

I run Microsoft Teams via Station and it is giving me a password error.  I first noticed this on the Ubuntu machine, but tested today on the Mac to the same result.

This is very odd as I also use One Drive and Outlook - and both use same login details (MS 365) amd the login works perfectly.

I then went and tested the login (copied and pasted to make sure I was typo free) into Chrome - no login issue at all.  I also (on Ubuntu) used the unofficial Teams client, logged in with no issues whatsoever.

I don't know what could cause this - it all goes to the same login process (username/pass, is this company account/personal - company - and then sends an Authenticator code).  As above, works flawlessly with Outlook, One Drive but not Teams via Station only.

**Comment by viktor44** [comment]
#411
