### ISSUE TITLE
Teams login error

### ISSUE THREAD

**Issue by holmstrands** [getstation/desktop-app#411]
- Application version: 3.0
 - OS: MacOS 14.4.1

I get an error when trying to login to Teams. 
It uses the same credentials as my Outlook account and that works. 
I tried to login with different methods but nothing works.

**Comment by mattinvietnam** [comment]
Same issue here (reported a couple of days ago as well on both Mac and Linux versions)

Wonder if issue is related to this:
https://learn.microsoft.com/en-us/microsoftteams/new-teams-web

**Comment by teampollinate** [comment]
I also have an issue where it is not finding my account when I try to login to Teams. I assume this is because I have an Office 365 for business account rather than personal?

**Comment by Keltirion** [comment]
Same for me. Created a custom app with this url https://teams.microsoft.com/v2/?clientexperience=t2 as workaround for now. For me it works.

**Comment by august159** [comment]
> Same for me. Created a custom app with this url https://teams.microsoft.com/v2/?clientexperience=t2 as workaround for now. For me it works.

Thanks for the workaround. I confirm that Outlook365 accounts are not recognized anymore in the official app.

Thanks in advance to the fixing team.
