### ISSUE TITLE
indeed will not verify human

### ISSUE THREAD

**Issue by markpsouthampton** [getstation/desktop-app#421]
Hi
It will not verify im human using cloudflare when accessing account
Windows 11

- Application version: _[e.g. 2.2.1]_
 - OS: _[Windows 10, MacOS 13.4, CentOS 7 ...]_

**Steps to Reproduce:**

**Screenshots**

**Comment by viktor44** [comment]
Error description is unclear.
Please fill Steps to Reproduce
