### ISSUE TITLE
Use Tool Tips for Apps

### ISSUE THREAD

**Issue by JeremyGadd** [getstation/desktop-app#424]
It would be great if there could be some indication of which app it is when you move the mouse over it. I have created a few custom apps and it's not often clear which one it is if it is using a generic icon. A tool tip that gives the app name would be helpful. Thanks

**Comment by blazlesnik** [comment]
I agree. Please, add this possibility soon! It's realy annoying to identify which application stands under certain icon.

**Comment by viktor44** [comment]
#364
