### ISSUE TITLE
Notifications on Mac

### ISSUE THREAD

**Issue by Norgul** [getstation/desktop-app#426]
Hi, for some reason I am getting no notifications whatsoever.

Things I've checked on Station:
- Do not disturb mode is turned off
- App-specific notifications (bell icon on app) are allowed and not turned off
- General notifications (bell icon in sidebar bottom) are allowed and not turned off

Things I've checked on Macbook:
- Focus mode is turned off
- Notifications are generally available
- There is no Station listed under my apps to allow notifications specifically for it

I have Macbook Pro M1 on Sonoma 14.16.1. 

Station version 3.1.0
Electron27.3.11
Chrome118.0.5993.159
Node18.17.1
v811.8.172.18-electron.0

Any ideas what could be wrong? App is great, but having no notifications will unfortunately be a deal breaker for me :/

**Comment by viktor44** [comment]
Do you receive notifications if you open the application in a browser?
By the way, from which application do you want to see notifications?

**Comment by viktor44** [comment]
Closing the ticket due to inactivity
