### ISSUE TITLE
User Agent reports as MacOS on Windows

### ISSUE THREAD

**Issue by ajgold** [getstation/desktop-app#429]
- Application version: 3.1.0
 - OS: Windows 11

**Steps to Reproduce:**

1. Go to Station Settings
2. Click on an application and activate Background Activity
3. Using another service, capture the User Agent making requests (I was using Cloudflare's WAF)
4. Note that the application reports as:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.289 Safari/537.36

This is largely a transparent issue and doesn't affect any functionality but makes it more difficult to identify request sources.

**Comment by viktor44** [comment]
I don't think we have time to implement it in the nearest future 
Anyways PR is welcomed
