### ISSUE TITLE
Feature to Specify App Instance Name and Icon

### ISSUE THREAD

**Issue by ahmadtechnik** [getstation/desktop-app#430]
First of all, I would like to thank you for this great app. It has been incredibly useful in managing multiple web app instances in one window.

I have a feature request that would greatly enhance the user experience. It would be fantastic if users could specify the icon and title for each app instance. For example, I personally have multiple WhatsApp instances open at once, and it can be difficult to quickly identify which instance I need to interact with. Being able to customize the icon and name for each instance would make it much easier to navigate between them.

Additionally, it would be helpful to have a popover tooltip for each instance that shows the specified name for the instance when hovering over it. This small addition would make the workflow even smoother.

Thanks again for your awesome work on this app!

**Comment by viktor44** [comment]
#364
