### ISSUE TITLE
Browser version no longer supported by Slack

### ISSUE THREAD

**Issue by animatorkris** [getstation/desktop-app#432]
- Application version: 3.1
 - OS: MacOS 14.5 Sonoma

**Steps to Reproduce:**

1. Have Slack Added and Logged in
2. Click on Slack App Badge
3. Be informed that the version of the browser is no longer supported by Slack
4. See picture -

**Screenshots**
<img width="922" alt="image" src="https://github.com/user-attachments/assets/2d5237e1-4d56-4911-ae25-cfa3ced22ea1">

**Comment by MrNDeYoung** [comment]
I'd also like to see a solution to this! I logged in today and was bummed to find Slack no longer working :(

**Comment by jonrick** [comment]
Setting up station on a new PC today and am getting the same error. Looks like a quick work around is updating the user-agent, but I'm just not familiar enough with the code base to do this locally.

I'm gonna poke around but incase someone beats me to it, this should work for the user-agent:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Slack/4.39.90 Chrome/127.0.6533.72 Electron/13.1.9 Safari/537.36

**Comment by daveaglick** [comment]
If you figure out how to patch the current version of Station @jonrick, let us know! Managing a bunch of different Slacks alongside a bunch of different Discords was one of my main uses for Station, so I was disappointed to see this error message this morning.

**Comment by jonrick** [comment]
It looks like it's fairly easy to override the user-agent, here is an example for YouTube Music:
https://github.com/getstation/desktop-app/blob/183d1ffa96dcac721e9a1796ed63b3ca1da6fb38/packages/app/manifests/definitions/14830.json#L13

Which we should be able to update Slack's manifest:

https://github.com/getstation/desktop-app/blob/183d1ffa96dcac721e9a1796ed63b3ca1da6fb38/packages/app/manifests/definitions/21.json

I just haven't had a chance to pull the repo and put together a PR.

**Comment by jthadden** [comment]
Hey there,

this is really a blocking issue in that case, but we had this before already (I think with gchat) and I wonder, why we do not expose the user agent setting per app/app-instance? This would solve the problem also for the future and other apps...

Cheers,
     Joachim
