### ISSUE TITLE
Slack is not working any more due to "outdated" browser

### ISSUE THREAD

**Issue by jthadden** [getstation/desktop-app#433]
- Application version: 3.1.0
 - OS: Fedora 40

**Steps to Reproduce:**

1. Add Slack as an App
2. Add a normal Slack Workspace
3. Login
4. Click the button to open up the workspace in the browser
5. It will just reload the same page

Any old Slack apps are just showing the "Sorry, your browser is not supported" and links to the desktop or mobile apps.

**Comment by calroscow** [comment]
Happening for me as well, same app version, OS: Sonoma 14.6.1

**Comment by viktor44** [comment]
#432
