### ISSUE TITLE
Can't load App store on desktop app

### ISSUE THREAD

**Issue by AstroZelda** [getstation/desktop-app#44]
I can't seem to access the app store anymore, it's been going for a solid 3 months now.
I am always greeted by this page : \
<img src="https://user-images.githubusercontent.com/22789592/132695185-d23f22d1-3fbc-42e6-a0b0-ddf8c455734b.png" data-canonical-src="https://user-images.githubusercontent.com/22789592/132695185-d23f22d1-3fbc-42e6-a0b0-ddf8c455734b.png" width="400" height="300" />

**Comment by jsavin** [comment]
@AstroZelda that message would appear if you're still using the now defunct commercial version of the app. The app store works in the current [release version](https://github.com/getstation/desktop-app/releases) on Github, which is v2.0.9 as of this writing.

**Comment by AstroZelda** [comment]
Hello @jsavin 
I am now on v2.0.9 as you suggested, and now I can't use Telegram nor Discord anymore...
But that is another subject 😛 

Thank you, have a nice day

**Comment by WillyReyno** [comment]
I can't load Discord either, @AstroZelda did you find a workaround?

**Comment by AstroZelda** [comment]
@WillyReyno I... err, kinda x) I use another app now
