### ISSUE TITLE
Discord screen sharing not working

### ISSUE THREAD

**Issue by gabimig** [getstation/desktop-app#441]
Hello I appreciate Station very much it is very useful to me, but I have here a little misfunction for discord:

Version:
Stationversion 3.1.0
Electron27.3.11
Chrome118.0.5993.159
Node18.17.1
v811.8.172.18-electron.0

OS: windows 11

**Steps to Reproduce:**

1. Open Discord with and login
2. Enter a channel
3. Press share screen button
4. As you can see nothing happens

**Screenshots**
There is nothing to screenshot, nothing happens

**Comment by viktor44** [comment]
#95
