### ISSUE TITLE
screen mirroring dont work

### ISSUE THREAD

**Issue by Contessafry** [getstation/desktop-app#444]
- Application version: _[e.g. 2.2.1]_
 - OS: _[MacOS 13.4]_

**Steps to Reproduce:**

on macOS I can't perform screen mirroring on any app I've used so far (discord and slack)
please it would become the perfect client it saves me a lot of resources

**Comment by tomasz-grabowski-netbulls** [comment]
Same issue here. Screen sharing in Slack huddles doesn't work.

**Comment by viktor44** [comment]
#95
