### ISSUE TITLE
Whatsapp tag name

### ISSUE THREAD

**Issue by riteshpahuja** [getstation/desktop-app#447]
Hi,

Station is awesome, station is where I station my office.

I wanted to ask can I change the whatsapp name for tag some other name so that I can get easily identify form which number my whatsapp is running , as I am using multiple whatsapp in station an
![image](https://github.com/user-attachments/assets/24d0275e-7b38-40cb-8f87-efd1f5ca2686)
Like i have attached Rambox image which having option to tag a name

Thanks in advance

**Comment by viktor44** [comment]
#364
