### ISSUE TITLE
Feature Request: Option to close entire window with Cmd+W shortcut

### ISSUE THREAD

**Issue by rdewolff** [getstation/desktop-app#448]
Hi there! 👋

First, thanks for this awesome project! I have a small feature request that I think would improve the user experience.

Currently, when using Cmd+W, it only closes the active station/app. It would be really helpful if we could have the ability to close the entire window with this shortcut, either as:

The default behavior, or
An optional setting in preferences
This would align better with many users' muscle memory from other macOS applications where Cmd+W typically closes the whole window.

Suggested Implementation:

Add a preference toggle: "Close entire window with Cmd+W"
Or make it the default behavior with Cmd+W, while perhaps using a different shortcut for closing individual stations
Would love to hear your thoughts on this! Let me know if you need any clarification.

Thanks for considering this request! 🙂

Cheers!

**Comment by viktor44** [comment]
IMO just a small inconvenience. I don't think we can implement it in the nearest feature.
I'm closing the ticket to keep backlog clean, but feel free to introduce the PR.
