### ISSUE TITLE
Can't log into Slack, redirect loop

### ISSUE THREAD

**Issue by jsavin** [getstation/desktop-app#45]
I just set up a new install of the latest release v2.0.9, on macOS 10.15.7. I can't log into any Slack workspaces either using email/password or Google authentication. Authentication appears to succeed, and then Slack loads a page with this message "To use Slack, you'll need to update your browser or download the app" and saying it's opening the workspace in the Slack app.

If the Slack app is installed, then it's launched/activated with the workspace logged in there instead of in Station. If I move Slack.app to the trash, then the newly logged in workspace shows the same page and continually redirects back to the page over and over again. Clicking on the link to open the workspace in the browser just reloads the same page again.

Some workspaces seem to work some of the time, which may mean that Slack is gradually rolling a change out on their servers to enforce old browser version deprecation. I assume this is related to Station being on an older version of Electron, and am aware that moving to the latest Electron is likely to be significant work.

Is there a workaround available where the user-agent could be spoofed so that Slack's servers think I'm running a more recent browser version? Slack's system requirements [page](https://slack.com/help/articles/115002037526-System-requirements-for-using-Slack) indicates at least Chrome v83, Firefox v78, Safari v14, or Edge v84 is required.

**Comment by samir-madan** [comment]
Facing the same error at my end as well.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
