### ISSUE TITLE
Read this if you wonder why your Station stopped working

### ISSUE THREAD

**Issue by DuMaestro** [getstation/desktop-app#46]
This month Station stopped working for me in Google Chrome, I finally found out why.

Message of one of the founders of Station:

https://medium.com/@julien_26779/handing-station-to-mankind-b1225e4e7413

Thank you team Station for making my digital life easier for the last couple of years. Hopefuly someone can continue this great project!

**Comment by aaddi19** [comment]
THANKS! what do you use now?

**Comment by DuMaestro** [comment]
Nothing yet, maybe will use Wavebox (paid) again. You?
