### ISSUE TITLE
can not add new apps

### ISSUE THREAD

**Issue by aaddi19** [getstation/desktop-app#48]
![image](https://user-images.githubusercontent.com/90679654/133213666-99955578-abcc-4421-bebb-d031025c74f2.png)

**Comment by kchang2021** [comment]
I am experiencing the same issue - deleted my Slack app as it would not function anymore and attempted to readd the app, but got the above error message

**Comment by subokita** [comment]
Same here.

**Comment by iefuji** [comment]
Same here.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
