### ISSUE TITLE
Many issues with Slack since this morning

### ISSUE THREAD

**Issue by collectrice** [getstation/desktop-app#52]
Hi, this morning I couldn't sign it to Slack anymore and once deleted, couldn't add any more apps.
I uninstalled Station and reinstalled, and now when I try to open Slack on Station, I get this message (screenshot), and it sometimes opens the slack app itself in its own window, not within station.

I can't connect my whatsapp account (screenshot).

Messenger appears as "offline", and old messages aren't loading. (screenshot)

What is going on and how can I fix this ?

Thank you !

<img width="712" alt="Screenshot 2021-09-16 at 10 38 40" src="https://user-images.githubusercontent.com/90835656/133592047-f79da4c4-8da5-4425-b9d1-36f4636f3595.png">

<img width="1085" alt="Screenshot 2021-09-16 at 10 38 32" src="https://user-images.githubusercontent.com/90835656/133592150-461741ee-3ec4-4759-8f4f-4feca1626b03.png">

<img width="840" alt="Screenshot 2021-09-16 at 11 57 27" src="https://user-images.githubusercontent.com/90835656/133592277-4caa6e40-fce0-434c-9891-8795d0239643.png">

**Comment by collectrice** [comment]
Hellllp, is anyone seeing this ?

**Comment by taraloum** [comment]
I had the same issue today! It's nice to hear I'm not the only one, but it sucks because I'm not sure what to do! Btw don't download slack on your desktop, I did that and it totally messed up my computer. It kept opening by itself and I had to uninstall it and shut down my computer. Anyway let me know how it goes for you!

**Comment by collectrice** [comment]
I don't get why no one from Station is responding, this is so depressing :(

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
