### ISSUE TITLE
The "use Slack in your browser" link doesn't do so

### ISSUE THREAD

**Issue by BayAreaData** [getstation/desktop-app#53]
When I try to sign into a Slack workspace it gives me the option to "Open Slack" to use the desktop app, or "You can also use Slack in your browser." with the latter half of the sentence a link to open in browser. Except when you click that link... it still opens the app. And uninstalling the app sends it into an endless loop of reloads.

While different than the previous "browser is unsupported" error it's a lateral move at best.

**Comment by Serubin** [comment]
Seconding this - this is an unfortunate issue

**Comment by robinusesgithub** [comment]
same here. can't actually find a setting within slack to disable the connection either.

**Comment by bgscheiner** [comment]
Confirming, same issue. Tried to add slack integration in Station with slack app installed on machine (mac). Loads "Click "Open Slack" to launch the desktop app.
Not working? You can also use Slack in your browser." with link as described above. The desktop app then launches.
Uninstalling the app then clicking the link reloads that screen within Station.

**Comment by BayAreaData** [comment]
There's nobody actually working on Station at this point, is there? I'm getting the sinking feeling the developers open-sourced it broken and didn't make any effort to support the transition and build a community around actually working on it.

**Comment by kylejericson** [comment]
Yes same issue here.

**Comment by vbinimelis** [comment]
+1 same issue

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
