### ISSUE TITLE
Cannot login to station

### ISSUE THREAD

**Issue by Xpistos** [getstation/desktop-app#54]

**Comment by Xpistos** [comment]
![station](https://user-images.githubusercontent.com/417991/134102158-4957e7fa-921b-470b-b2ff-72796f34e7ba.png)
![Screenshot from 2021-09-20 21-20-44](https://user-images.githubusercontent.com/417991/134102258-3b68a76e-7660-4c0d-965c-ee5bdce6d97a.png)

**Comment by Xpistos** [comment]
Nothing huh?

**Comment by viktor44** [comment]
Nothing. This issue is deprecated. Open source version of Station works without authorisation.
Try [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
