### ISSUE TITLE
Netflix App Error M7701-1003

### ISSUE THREAD

**Issue by dmetzler1988** [getstation/desktop-app#55]
Hi,

when i would like to start a stream on Netflix, i alltimes receive this error: https://help.netflix.com/en/node/27451

Could you please fix it? 
Maybe activate the described setting for Netflix app or make an update, if it can be done easily.

Or is there any workaround for it what i can do in Station App?

Version which is installed on latest MacOS
Stationversion 2.0.9
Electron7.3.3
Chrome78.0.3904.130
Node12.8.1
v87.8.279.23-electron.0

**Comment by viktor44** [comment]
Does Netflix app work in 2.1.0?
