### ISSUE TITLE
Whatsapp not showing a QR code

### ISSUE THREAD

**Issue by Jdinger03** [getstation/desktop-app#56]
[log.log](https://github.com/getstation/desktop-app/files/7205534/log.log
(https://i.gyazo.com/6102d20328f809f38547855a05eea03e.png)
When attempting to connect a mobile device to WhatsApp for the first time, the pairing QR code never loads. Attempted fix using the "Reset Current Application" button, to no avail. Other apps work fine.

**Comment by sven-ahrens** [comment]
This is a known issue: https://github.com/getstation/desktop-app/issues/3

**Comment by al22xx** [comment]
I have the same issue QR not loading can we please have a fix....Whatsapp is my most use app on Station

**Comment by tigrax11** [comment]
Cinfirm the same problem on Chrome and Opera. Pls. fix ASAP.

**Comment by Safi-services** [comment]
it's been 10 days since the WhatsApp problem was posted, but it's still happening

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
