### ISSUE TITLE
Signal integration

### ISSUE THREAD

**Issue by mateuszjarzyna** [getstation/desktop-app#57]
It would be nice if there was integration with [Signal](https://signal.org)

**Comment by Smithbc** [comment]
Does anyone know if there is a possible work around to integrate Signal or if this integration is planned in the near future?

**Comment by EarnU21** [comment]
+1, that would be awesome!

**Comment by Ethahegao** [comment]
+1, I am very interested in this

**Comment by HectorMendez** [comment]
+1, I am very interested i use Signal every single day

**Comment by aloxe** [comment]
it's a big want for me too but Signal doesn't offer and will not offer a web integration for security reasons.
https://community.signalusers.org/t/google-to-retire-chrome-apps-what-will-be-with-signal-desktop/469/6

I do hope this may be possible to include a deskop app in Station.  @magne4000?
