### ISSUE TITLE
HubSpot loading fails - browser check loops without redirecting

### ISSUE THREAD

**Issue by ternie2** [getstation/desktop-app#58]
I am running MacOS 10.14.6
Station version 2.0.9
> Electron7.3.3
> Chrome78.0.3904.130
> Node12.8.1
> v87.8.279.23-electron.0

When I click on the HubSpot app it fails to get past the browser check process.
New to Station (loving what it can do so far btw), but this error looks similar to an issue I've also encountered running Shift (fixed in their Beta version).

<img width="792" alt="Screen Shot 2021-09-24 at 17 34 46" src="https://user-images.githubusercontent.com/91312664/134637962-b2f416e7-63cd-45aa-8b11-2946c5a46f50.png">

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
