### ISSUE TITLE
Unable to add Gmail business account

### ISSUE THREAD

**Issue by NiviAppno** [getstation/desktop-app#59]
fresh install on mac big-sur
Station version v2.0.9

Gmail auth error:
Error 400: invalid_request
Missing required parameter: client_id

**Comment by convertl** [comment]
Hello,
I get the same error with personnal Gmail account and windows new Station installation

**Comment by NiviAppno** [comment]
I checked my personal account, and also completing the auth in incognito, all with the same failure message

**Comment by Orbital101Studio** [comment]
Same problem here. All google Apps dont work with business and personal accounts providing the same error message : 

Gmail auth error:
Error 400: invalid_request
Missing required parameter: client_id

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
