### ISSUE TITLE
Can't sign into Google Account with Advanced Protection Enabled i.e accounts that use a hardware token keyfob

### ISSUE THREAD

**Issue by omega-inspiron** [getstation/desktop-app#6]
Getting a client_id missing error when trying to sign into my google account. This was available in the previous version of station.

**Comment by directionforward** [comment]
Seems to be a general Google authentication issue, see https://github.com/getstation/desktop-app/issues/2

**Comment by omega-inspiron** [comment]
Thanks for the update.

**Comment by magne4000** [comment]
Closed in favor of #2
