### ISSUE TITLE
Google apps dont allow to login : Gmail auth error: Error 400: invalid_request Missing required parameter: client_id

### ISSUE THREAD

**Issue by Orbital101Studio** [getstation/desktop-app#60]
Error with all google applications on Station, when trying to login with both business and personal accounts, i get the following error message : 
Gmail auth error:
Error 400: invalid_request
Missing required parameter: client_id

The problem have been reported by other users already, please fix it as soon as possible as it becomes a serious disadvantage

**Comment by slopezmarcano** [comment]
Same problem happening here. 

Authorisation Error
Error 400: invalid_request
Missing required parameter: client_id

Tried safari and chrome and same problem

**Comment by alexitheodore** [comment]
I am a new user, just downloaded - having the same issue. Tried with several different gmail accounts using both 2.0.8 and 2.0.9.

**Comment by joeknouse** [comment]
Getting this as well, with the mac version.

**Comment by nikbonne** [comment]
Same problem for me when trying to login to Google Calendar.

**Comment by calevio** [comment]
Happening here in Windows 10 for Google calendar

**Comment by faroe2k9** [comment]
I have the problem as well. Tried Gmail, Calendar. Please fix asap...

**Comment by aschrammel** [comment]
Can confirm the issue on Mac OS as well.

**Comment by thomasgentilhomme** [comment]
Same issue on Mac OS 11.6

**Comment by cici** [comment]
Same with Mac OS 11.4.

**Comment by sabgaby** [comment]
Same with Mac OS 11.4, trying to sign in with a Google Workspace account

**Comment by Jottoya** [comment]
I'm getting that code as well when trying to Sign in to Google. In addition to this, it seems like Station cannot connect to anything at all... every app I try to load and add, the loading circle just spins there. Not sure if anyone else is having just this issue or a combination of both. Thanks

**Comment by davioliveira-dev** [comment]
is there any alternative? there are too many active problems and no solution

**Comment by vdrover** [comment]
@davioliveira-dev Try Rambox.

**Comment by tigrax11** [comment]
I confirm having the same problem on Chrome and Opera. Pls. fix ASAP.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
