### ISSUE TITLE
Discord not loading

### ISSUE THREAD

**Issue by WillyReyno** [getstation/desktop-app#64]
Hello, 

I tried to add Discord service, but I'm stuck on the Discord loading screen. 

I'm running Station v2.0.9 on MacOS Big Sur 11.5.2

The following error is displayed in the console of the Page Developper Tools : 
```
WebSocket connection to 'wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream' failed: Error during WebSocket handshake: Unexpected response code: 404
```

![Capture d’écran 2021-10-02 à 18 05 24](https://user-images.githubusercontent.com/5576482/135724120-993843c0-5cbf-4ae7-8084-c94f7e3407f5.png)

Thanks for your help

**Comment by macdabby** [comment]
I have tried several services and I eventually get stuck on a wss request. I wonder if this is a bigger issue than discord and just a basic wss handling issue? I'm using Station 2.0.9 on Debian 11 with Gnome using Appimage

**Comment by netthier** [comment]
Also happens on Station 2.0.9 on Windows.
