### ISSUE TITLE
whats app

### ISSUE THREAD

**Issue by syfer1987** [getstation/desktop-app#66]
see pic 
fresh install 
![image](https://user-images.githubusercontent.com/47603252/135914678-43e4f5cb-8f6a-4df6-b09c-2e8f8e4580c4.png)
readind does not fix problem

**Comment by andreascarfo** [comment]
My problem is this
![immagine](https://user-images.githubusercontent.com/41382786/136046012-498abbc2-834a-4f1a-b89c-eb422c574979.png)

**Comment by sergSCys** [comment]
> 
> My problem is this, while on the browser I get the qr code on Station the ring rolls on and on. ![immagine](https://user-images.githubusercontent.com/41382786/136046012-498abbc2-834a-4f1a-b89c-eb422c574979.png)

I'm having the same issue with WhatsApp - and I want to note that it is working on Firefox.
Also, Discord won't manage to connect.

**Comment by BeanzOnToast** [comment]
Jus to add to this, I get an error saying whatsapp works with v60+ of chome. Assuming the underying browser launching the apps needs to be updated here. 
![image](https://user-images.githubusercontent.com/61152169/162326897-c296c1df-1874-4499-95c9-017e910bb591.png)

**Comment by BeanzOnToast** [comment]
Looks like #9 is the culprit.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
