### ISSUE TITLE
facebook message 

### ISSUE THREAD

**Issue by syfer1987** [getstation/desktop-app#67]

**Comment by syfer1987** [comment]
![image](https://user-images.githubusercontent.com/47603252/135915204-6aeb07f8-b908-48fa-a3e1-36e06bda87ed.png)

**Comment by syfer1987** [comment]
fresh install

**Comment by kuck1u** [comment]
Hi.

Facebook & Instagram is temporarily out of service due to a system failure.

**Comment by viktor44** [comment]
#143
