### ISSUE TITLE
Twitter / Gmail login

### ISSUE THREAD

**Issue by lorenmj** [getstation/desktop-app#68]
On new install I added GMAIL and TWITTER apps, but I cannot login to either. I'm using POP! OS and installed Station from the web download. Deb version and used command line sudo apt install -f ./Download/Station-download.deb.

Nothing I do seems to allow me to login to either service. Gmail starts a firefox web browser, if I login it gives me an error. On twitter it loads the main twitter page (that it shows if you are not logged into twitter). When I click login it takes away the "login" link and still shows the main page. I cannot login, it seems to have a problem showing me this login page.
![Screenshot from 2021-10-04 15-55-23](https://user-images.githubusercontent.com/11542996/135923673-65c1ea37-a103-4b85-8787-2b3495c43c13.png)

**Comment by Malkierian** [comment]
Same for Gmail. Says

Error 400: invalid_request
Missing required parameter: client_id

**Comment by andreascarfo** [comment]
#metoo !

**Comment by fa-nethers** [comment]
Agreed also seeing Error 400 on gmail: Error 400: invalid_request
Missing required parameter: client_id

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
