### ISSUE TITLE
Issue with images/ logos ?

### ISSUE THREAD

**Issue by sergSCys** [getstation/desktop-app#69]
![image](https://user-images.githubusercontent.com/70575132/136091669-57ebd0a0-74a7-4874-b3a2-51c004627602.png)

Logos won't load, and  it show the broken logo:

![image](https://user-images.githubusercontent.com/70575132/136091905-22e25f8b-a008-4b08-a6ed-a7cc3deeaa77.png)

Thank you!

**Comment by CheerChen** [comment]
I have 10+ custom apps and all turned into broken icons, don't know how to resolve without reinstalling Station.

**Comment by sergSCys** [comment]
> 
> 
> I have 10+ custom apps and all turned into broken icons, don't know how to resolve without reinstalling Station.

I did a reinstall and still broken - and i got with a couple more errors on loading apps.

**Comment by agpldev** [comment]
I take it there is still no resolution for this issue. I am seeing the broken apps issue, but the underlying apps seem to be working fine

**Comment by vincenttan5** [comment]
I've been experiencing broken icon with standard apps, whatsap, messenger, google, pretty much everything since many version ago.
