### ISSUE TITLE
Missing required parameter: client_id

### ISSUE THREAD

**Issue by ghost** [getstation/desktop-app#70]
Missing required parameter: client_id 
when registering google apps accounts

**Comment by AnaAzevedoHubs** [comment]
I have the same issue, with older versions as well. I tried v2.0.8 and v2.0.4 and got the same error.
I using mac big sur (v11.3.1)

I get this for every google suite app but I am able to login into Notion with google sign in

**Comment by tiklup11** [comment]
gotta switch if they have decided not to fix. : (

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
