### ISSUE TITLE
Issues with station

### ISSUE THREAD

**Issue by taraloum** [getstation/desktop-app#71]
What has been going on with Station! I can log into my station on my desktop app. I can't add any more apps. It won't even update properly. I don't understand why it's not working. I've also deleted it and downloaded a new version but the same issue happens again with it. What can I do???

**Comment by thibdonz** [comment]
Same issue

**Comment by kastapov** [comment]
Their web server with icons is down. More and more services are not working on the station. I found Ferdi as a good replacement for Station.
