### ISSUE TITLE
Google Authorization Error

### ISSUE THREAD

**Issue by balloondogspop** [getstation/desktop-app#74]
When I try to add Google apps to my Station, I receive the following error message:
Error 400: invalid_request
Missing required parameter: client_id

I'm using the desktop app on Windows 10.

<img width="355" alt="autherror" src="https://user-images.githubusercontent.com/92739130/137754892-bc64df75-1cf8-43c9-96ab-7f13455c133a.png">

**Comment by jdefgts** [comment]
I experienced the same error in attempting to set up station running Windows 10.

**Comment by NicoCaldo** [comment]
I can't even fill the password as Google answer with "this browser may be insecure, try another one"

**Comment by jdefgts** [comment]
FWIW, I am able to get to the Google authorization panel with the Edge browser.

**Comment by Seba678** [comment]
Please could someone solve the problem because it is a super useful and necessary tool

**Comment by jpye-finch** [comment]
plus 1

**Comment by MoElBehary** [comment]
same here !

**Comment by publicaciones** [comment]
same here!

**Comment by kitadesign** [comment]
same here!

**Comment by GabrielF11** [comment]
Same here on intel Mac.

**Comment by kvdv99** [comment]
same here, Windows 10, latest Chrome browser and latest Station release
Still no solutions to this?

**Comment by tiklup11** [comment]
Hey everyone, I found an alternative application FERDI.

**Comment by kvdv99** [comment]
Trying Ferdi now,  not impressed, I can't even create a new account!?  I fill in all fields +long/complex password, then I click the 'create account' button and nothing happens :(

**Comment by napter** [comment]
Just tried station for the first time - got this error and ended up here. Is there no way to log into gmail?

**Comment by n0pisang** [comment]
I dont think it going to be solved soon. So I use Stack now. I’m quit satisfied with it. 
I did tried Ferdinand and Franz but it was way to heavy for my MacBook.

**Comment by goodyis** [comment]
Creating your own app in station and pointing it at accounts.google worked.

See previous ticket for specifics.

**Comment by joncline** [comment]
Same issue for me. The workaround [above](https://github.com/getstation/desktop-app/issues/74#issuecomment-968365159) does work though it reduces the value of the app directory.

**Comment by napter** [comment]
I tried that but I couldn't add two separate accounts - when I added it twice they both seemed to share cookies and I was logged in to the same account in both. I'm using [Ferdi](https://github.com/getferdi/ferdi) now, also free and open source and it is working great so far.

**Comment by n0pisang** [comment]
> I tried that but I couldn't add two separate accounts - when I added it twice they both seemed to share cookies and I was logged in to the same account in both. I'm using [Ferdi](https://github.com/getferdi/ferdi) now, also free and open source and it is working great so far.

I was struggeling with that too. But then Idiscovered that you can set it in private tab with the tree dots in the right upper corner of your tab. So then you can use as many accounts as you like.

**Comment by yuanchueh** [comment]
I just downloaded today on Windows 10. Tried both Chrome and Edge to authenticate my Google Account (Personal and Business). All failed with the error above.

**Comment by peteshaw** [comment]
This is ridiculous.  A similar app for Linux called Tangram does not have this issue, and on Station simply creating a custom app and pointing it at mail.google.com works fine.  So the gmail app is broken, and it appears to be deliberately so, because something was introduced that is different from the default that brakes this.  This cannot be a difficult thing to fix.

**Comment by rohunmsharman** [comment]
has anyone tried to debug it yet?

**Comment by u6tory** [comment]
Same on M1 Macbook Pro
is this project not on maintaining?

**Comment by austin3410** [comment]
Yup same here on Windows 11. It does work when you add it as a custom app pointing to https://mail.google.com but the isolation isn't there so if you add the app again it just loads to the same account as the first app.

I guess no ones supporting Station at this point?

**Comment by napter** [comment]
> I guess no ones supporting Station at this point?

Yes that seems to be the case. Try ferdium https://github.com/ferdium/ferdium-app

**Comment by joncline** [comment]
I use Shift at this point.

jc

Jon Cline
***@***.***
www.linkedin.com/in/joncline
626-400-6281

Sched call: http://book.joncline.com

**Comment by mikejpaterson** [comment]
Looks like an issue with OAuth - it makes the app unusable for me.

**Comment by jjhartmann** [comment]
Same for me. On Win 10 Desktop. Any updates on this?

**Comment by anarbelaez** [comment]
Same here

**Comment by doanchungtu95** [comment]
There is no bugfix till now. Mac M1

**Comment by Seiifer** [comment]
Same here.

One year since the last commit.
I'm guessing station is no no longer maintained ?

**Comment by carsondarling** [comment]
Given that the top of the readme has said "This project is not actively maintained" since February 11, 2022, I think it's a safe bet to believe that it's no longer maintained.

**Comment by joncline** [comment]
Agreed. I've moved to Wavebox which is well worth the $100/year.

Jon Cline
***@***.***
www.linkedin.com/in/joncline

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
