### ISSUE TITLE
Wrike Connectivity Issue

### ISSUE THREAD

**Issue by balloondogspop** [getstation/desktop-app#75]
I am able to add Wrike and sign in. However, Station is unable to maintain a steady connection with Wrike's servers. 
<img width="740" alt="wrike" src="https://user-images.githubusercontent.com/92739130/138747996-4f3a9b48-9fb0-4445-a221-5a27c1e77060.png">

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
