### ISSUE TITLE
Cannot Add Gmail into Station

### ISSUE THREAD

**Issue by masteronecos** [getstation/desktop-app#79]
I am trying to connect my Gmail account to Station and I get an error.
<img width="587" alt="Screenshot 2021-11-02 at 11 28 02" src="https://user-images.githubusercontent.com/12608077/139822200-73cd2173-31da-4f85-a3cd-f215b420acef.png">

**Comment by bzhqualite** [comment]
same here

**Comment by DawidWenderski** [comment]
And same here... Glad I am not alone with this :-)

**Comment by DEV-JWebers** [comment]
To me it does not let me access any Google service, nor does it load the QR Whats app, just installed on macOS Monterey.

The error says that the browser I'm using is not secure, try another one.

**Comment by GabrielF11** [comment]
Same here. Very disappointing.

**Comment by rost100x** [comment]
same

**Comment by orgo89** [comment]
Same here... There is no way to add a google account.

![Screenshot_20211105_122603](https://user-images.githubusercontent.com/4247876/140560649-157ca92b-336b-4586-a31a-9855d0ae05c1.png)

**Comment by MarinoPan** [comment]
there is a workaround behind this problem, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

**Comment by Soliloquist-1** [comment]
> there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

Worked like a charm, thank you!

**Comment by thibdonz** [comment]
Great thank you so much it's working perfectly just a bit boring when we want to use several Google accounts. 
Station is losing all is added value :(

**Comment by kvdv99** [comment]
Thanks for the workaround!  So only Whatsapp remains an issue now: no QR code appears on screen :(

**Comment by webenadam** [comment]
Is this app maintained?

**Comment by GabrielF11** [comment]
> Is this app maintained? 

I though so... if there are then the maintainers must not be checking the issues.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
