### ISSUE TITLE
Links open File Explorer instead of browser

### ISSUE THREAD

**Issue by mtschudi** [getstation/desktop-app#8]
This has been a long standing issue that hopefully can be resolved now that Station is open source. Often when clicking links, they open the File Explorer instead of opening in the default browser. I've never had a single link I want to open File Explorer, so hopefully that behavior can be changed.

**Comment by viktor44** [comment]
Is it still an issue?

**Comment by viktor44** [comment]
I'm closing the ticket. It's too old
We will create a new one if it is still an issue.
