### ISSUE TITLE
AppImage Fails to start

### ISSUE THREAD

**Issue by jacobamey** [getstation/desktop-app#82]
### Process

1. Download [AppImage](https://github.com/getstation/desktop-app/releases/latest/download/Station-x86_64.AppImage) 
2. mv Download/Station-x86_64.AppImage /opt
3. chmod +x Station-x86_64.AppImage
4. ./Station-x86_64.AppImage

#### My System

- Fedora 35 (Workstation)
- Kernel: 5.14.16-301.fc35.x86_64
- Gnome version 41.1
- Running X11
   - version 11.0
   - X.Org version: 1.20.11

#### Error When running App Image
```bash
./Station-x86_64.AppImage
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[23040:1108/115844.469867:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
[1]    23040 trace trap (core dumped)  ./Station-x86_64.AppImage
```

**Comment by KaKi87** [comment]
Hello,
I only got the first message on Linux Mint 19.3 but no launch either.
Thanks

**Comment by Falciform** [comment]
Same problem except that it was installed/launched with appimagelauncher.
I'm on the same OS, also Gnome 41 and X11.

`./Station-x86_64_7c0df140ea727d18b16a1bff66cc3da2.AppImage
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[4313:1227/083229.800117:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.`

**Comment by TDiblik** [comment]
Hi, I was able to get it running using
```
chmod a+x ./Station-x86_64.AppImage
sudo ./Station_x86_64.AppImage --install --no-sandbox
```
However, I'm new to linux and do not understand how AppImages work. I used these commands in my Downloads folder. Output seemed to contain errors that look like this:
```
[09:12:22.910] [info] File: 20180227185500-add-notification-pref.js.map does not match pattern: /\.[jt]s$/
```
for basically every file that this application is build from.
When running without sudo, the error output looked like this:
```
$ ./Station-x86_64.AppImage 
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[32075:0417/092544.349038:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.
Trace/breakpoint trap (core dumped)
```
Also, I was unable to build from the source code, because of node-gyp error that's caused by electron 17 and up.

My system:
Linux 5.15.32-1-MANJARO
