### ISSUE TITLE
Is this app still being mantained?

### ISSUE THREAD

**Issue by Tashima42** [getstation/desktop-app#83]
Hi! 

Station is an awesome app, and I would really like to use it, but I noticed that there's some issues and the last commit was 4 months ago, is Station discontinued? Are the team accepting PRs?

Tks!

**Comment by Ziris85** [comment]
Looks like, according to this post when they open-sourced the software, they were walking away from it entirely:

- https://medium.com/@julien_26779/handing-station-to-mankind-b1225e4e7413

> We have decided to go work on different projects in the future but some of you in the past had asked us to make our code open-source so you could contribute. While we have decided to end the adventure, there are still many of you using the app every single day, all over the world. We could have simply shut it down. But we’d rather hand it to the world for free and see our mission live on past our own creation.
