### ISSUE TITLE
OAuth 2.0 error.

### ISSUE THREAD

**Issue by ImNanni** [getstation/desktop-app#85]
Hello, my problem is that I cannot access my gmail account. The program opens a window in my browser to give access to google, but when I enter my account and password it shows me an authentication error, I have tried in other browsers and the same error always appears.

![image](https://user-images.githubusercontent.com/94270709/141666030-d9354580-f68b-4cb4-9afd-9331a535da94.png)

**Comment by judes3011** [comment]
yup! same issue here!

**Comment by sebaumonier** [comment]
Hello, i'm getting the same issue here. Downloaded the latest build today and could not setup the Google apps.

**Comment by dawaligora** [comment]
same here

**Comment by pbr0ck3r** [comment]
Seems like the developer, just forgot to add in their application client_id used for google SSO when using google's SSO API.

**Comment by danielmguerrero** [comment]
same here

**Comment by sirocco-fr** [comment]
Same here

**Comment by geekbleek** [comment]
Same here

**Comment by bigflave** [comment]
Also having the same issue, hopefully there is a fix soon

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
