### ISSUE TITLE
No Icons for Custom Apps

### ISSUE THREAD

**Issue by ghost** [getstation/desktop-app#87]
![image](https://user-images.githubusercontent.com/23508534/142178007-3dc7243f-db2f-4c75-af33-5eae761bb09f.png)

**Comment by iblueer** [comment]
I met a similar question
https://github.com/getstation/desktop-app/issues/84

**Comment by petejacobson** [comment]
I'm not getting any icons at all. I'm not seeing any updates for 5 months, is the project abandoned?

**Comment by eslicoenraad** [comment]
The same here on MacOS. Is there a timeline? Or is this project discontinued?

**Comment by jsanta** [comment]
Copying the image's URL leads to a AWS storage, which seems not to be working.

**Comment by ignacioaroche** [comment]
Is maybe abandoned?
