### ISSUE TITLE
Can't Connect Gmail Account

### ISSUE THREAD

**Issue by teojmciver** [getstation/desktop-app#89]
I tried connecting my G Suite account and I get the following error:

Authorization Error
Error 400: invalid_request
Missing required parameter: client_id

I work at a University that obviously uses a .edu email so I'm assuming the issue is with using OAuth 2.0 protocol.

**Comment by blackforestcode** [comment]
Same here.

Appimage
OS: Linux (Ubuntu 20.04 / Zorin OS)

**Comment by alecive** [comment]
Same. I'm on windows. Neither work nor personal gmail work

**Comment by hmujib** [comment]
Same here, Google returns a 400

**Comment by blackforestcode** [comment]
> copied from a previous thread:
> 
> there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

Doesn't work for me. Same problem as mentioned above.

**Comment by ronnymeli** [comment]
> copied from a previous thread:
> 
> there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

While this works it becames a nightmare because you can never use the usual HOME link.

**Comment by doomicle** [comment]
![Station](https://user-images.githubusercontent.com/43883799/143728756-7e4498c1-cb39-46b3-b178-59a0f383b089.png)

**Comment by dyanakiev** [comment]
same here

**Comment by starfight44** [comment]
**Copy from other thread**
 hixair commented on 26 Oct •

@ameliasellsmaine the Station team announced that they gave up on station development, that they made it open source for anyone that would want to update it. Meanwhile, Google and Slack changed their browsers requirements and now station is broken.
It always was a "free" app, I don't think we can demand that fix are made.
There are alternatives like Rambox and Franz (but not as good as station) .

**Comment by skylatian** [comment]
same issue here, obviously. Win11, chrome, newest station

**Comment by uksurd88** [comment]
Same issue here? no hot fix from the team?

<img width="331" alt="Screenshot 2021-12-01 at 13 06 26" src="https://user-images.githubusercontent.com/183840/144231991-66e051dd-997a-4644-8751-2b74bde2d6bb.png">

Station Ver : 2.0.9
mac OS : Monterey (12.0.1)

**Comment by kvdv99** [comment]
> > copied from a previous thread:
> > there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.
> 
> While this works it becames a nightmare because you can never use the usual HOME link.

I use it daily...  what do you mean with the usual HOME link?

**Comment by kvdv99** [comment]
> > copied from a previous thread:
> > there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.
> 
> Doesn't work for me. Same problem as mentioned above.

You probably selected gmail from the suggestions during the manual app creation,  don't do that

**Comment by kvdv99** [comment]
> there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

**Comment by kvdv99** [comment]
> same issue here, obviously. Win11, chrome, newest station

there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

**Comment by kvdv99** [comment]
> **Copy from other thread** hixair commented on 26 Oct •
> 
> @ameliasellsmaine the Station team announced that they gave up on station development, that they made it open source for anyone that would want to update it. Meanwhile, Google and Slack changed their browsers requirements and now station is broken. It always was a "free" app, I don't think we can demand that fix are made. There are alternatives like Rambox and Franz (but not as good as station) .

:(((

**Comment by kvdv99** [comment]
> Same here, Google returns a 400

there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

**Comment by SOMNiO-iNTERMEDiA** [comment]
For what it's worth, for any of those still struggling .. if you follow "kvdv99's" comment copied from a previous thread step-x-step, it does actually work:
1. Create a "Custom" App
A. click the "+" sign (bottom-left corner to add new apps)
B. click My Custom Apps, if it's not already highlighted (bottom of list on left)
C. click "+ Add A Custom App" button
D. enter App Name; click Next button
E. don't choose from suggested list; click Add button at bottom
F. choose App Color (use idrop) & choose any logo (stupid but but they're required)
G. enter "https://myaccount.google.com" (without quotes) in the Login URL field
H. you should see "Your app has been successfully added to your app store!" message; click Install Now button
4. Accessing Your Custom App
A. once installed, click on the new custom app icon in the left-margin
B. this should direct you to your main Google Account pageclick the checkerboard app box in the upper-right corner and choose Gmail. That will auto-create the Gmail icon / hot-button in the left-margin, below the Custom App icon.
Repeat the same for Calendar, Drive, Photos, Translate, etc.

**Comment by fabiograz** [comment]
> For what it's worth, for any of those still struggling .. if you follow "kvdv99's" comment copied from a previous thread step-x-step, it does actually work:
> 
>     1. Create a "Custom" App
>        A. click the "+" sign (bottom-left corner to add new apps)
>        B. click My Custom Apps, if it's not already highlighted (bottom of list on left)
>        C. click "+ Add A Custom App" button
>        D. enter App Name; click Next button
>        E. don't choose from suggested list; click Add button at bottom
>        F. choose App Color (use idrop) & choose any logo (stupid but but they're required)
>        G. enter "https://myaccount.google.com" (without quotes) in the Login URL field
>        H. you should see "Your app has been successfully added to your app store!" message; click Install Now button
> 
>     2. Accessing Your Custom App
>        A. once installed, click on the new custom app icon in the left-margin
>        B. this should direct you to your main Google Account page
>        C. click the checkerboard app box in the upper-right corner and choose Gmail
>        D. that will auto-create the Gmail icon / hot-button in the left-margin, below the new Custom App icon just created
> 
>     3. to create Calendar, Drive, Keep, Photos, Tasks, Translate, etc. you should just be able to go back to the Custom App and click on the checkerboard app box in the upper-right corner of your Google Account and choose which ever Google program you want to add to Station.
> 
> 
> Good luck!

Hi,
I've tried and work but if I want to add an other account when I click on "add an other account" it open a login page on the external browser. 

How I can add a second account?

Thanks.

**Comment by jonathanwsl** [comment]
I could get through with the customer link as above.  Thanks

**Comment by averyfreeman** [comment]
> > same issue here, obviously. Win11, chrome, newest station
> 
> there is a workaround, create new "app" and insert the link -> https://myaccount.google.com after connected, login into and click on icon in corner top right and click gmail -> after automatically will be redirect in app gmail of station logged in and you can remove the your custom app.

This worked for me and allowed me to use my yubikey for 2fa.  Then, when launching an instance of Calendar, Gmail, etc. it created a new app in Station on the left. Using MacOS 13.2.1.

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
