### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by mp3qwer** [getstation/desktop-app#90]
Would like to give it a try but I can't create an account.

If I try a google account I got a error message:
Fehler bei der Autorisierung
Fehler 401: deleted_client
The OAuth client was deleted.

If I try another provider than google I never get an acitivation mail

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
