### ISSUE TITLE
qr codes dont load

### ISSUE THREAD

**Issue by zogyboy** [getstation/desktop-app#91]
qr codes for telegram and what app dont show ever when you First set up so cant use them in station

**Comment by 1r0n51uv** [comment]
Same here on W11

**Comment by yunancun** [comment]
Same here for Telegram and Wp

**Comment by glimow** [comment]
Hi everyone, Same here for Telegram, Discord and Whatsapp on Apple Silicon MB Pro with a fresh Station Install from DMG

**Comment by tm140895** [comment]
Same here - W11 on a HP Spectre.

**Comment by kaylamillerdev** [comment]
same here. Windows 10 and discord. No QR loading so I had to sign in manually. and then I just get a spinning discord logo instead of it actually loading.

**Comment by fsenepin** [comment]
Same here on Whatsapp with Station version 2.0.9 on MacOS 12.01
QR code not loading.

**Comment by irfantony** [comment]
After reading this thread, the unresolved QR code for MacOS and Windows since Nov 30, 2021, I guess I have to continue using Rambox

**Comment by Delatorrea** [comment]
Same ware w11

**Comment by Younesssss** [comment]
Same here on ubuntu 20.04

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
