### ISSUE TITLE
Unable to login to Slack App

### ISSUE THREAD

**Issue by samir-madan** [getstation/desktop-app#92]
Hi All - I am unable to open the Slack app over the station. Stuck at page with below message after login to the workspace:

**Launching Goals101
Click "Open Slack" to launch the desktop app.
Not working? You can also use Slack in your browser.**

Tried workaround of creating a custom app and pasting the web address of the login page of Slack but getting below error mesage:

"We're very sorry, but your browser is not supported!"

Pls. advise if there is a workaround for the same.

**Comment by kaylamillerdev** [comment]
I'm getting a similar issue. Tried to login to slack and it tells me that the browser isn't supported.

**Comment by f2-107** [comment]
Same issuer here

**Comment by aleksanderwalczuk** [comment]
same here

**Comment by master-sushi** [comment]
Same here

**Comment by jamilnyc** [comment]
Same here. After reloading the page several times, I get this message:

```
Launching [My Team Name]
Click "Open Slack" to launch the desktop app.
Not working? You can also use Slack in your browser.
```

**Comment by adam-wood** [comment]
Station seems to keep launching/activating the desktop app, which I have installed (windows 11). This is the std behaviour from my web browser, but at least in the web browser I can click 'Use Slack in your browser' and it will work. This doesn't work in Station. I don't want to have to uninstall the slack desktop app in order to use Station.

**Comment by RMCampos** [comment]
+1

**Comment by jmertin** [comment]
Same issue here. Using the linux client deskop app.
Sometimes it proposed me to add the identifier into  Cut&Paste buffer and it worked. But there is no scheme for me to get there.

**Comment by drstaind** [comment]
Same issue - Station v.2.0.9 on Mac

**Comment by dianabarsan** [comment]
Same issue, Manjaro Linux.

**Comment by cabraljv** [comment]
same issue here

**Comment by cosmintanczel-jibecompany** [comment]
Same here
openSUSE Tumbleweed
Slack 4.23.0

**Comment by ruario** [comment]
Yep, me too

**Comment by cosmintanczel-jibecompany** [comment]
gr

**Comment by CTA-Jibe** [comment]
openSUSE Tumbleweed, Slack 4.23.0, same.

**Comment by ruario** [comment]
Perhaps this? https://stackoverflow.com/questions/70867064/signing-into-slack-desktop-not-working-on-4-23-0-64-bit-ubuntu/71062113

**Comment by stevematdavies** [comment]
Its almost 2023 here and the same problem persists OpenSuse TW latest. Problem is the same reagrdless of Browser or install method.

**Comment by fronald** [comment]
Same problem here.

**Comment by bordozer** [comment]
The same issue.

**Comment by viktor44** [comment]
@bordozer please do not use closed issues to report about your problems.
I've just checked Slack and it works fine for me.
