### ISSUE TITLE
Unable to login in Telegram

### ISSUE THREAD

**Issue by Nixgui** [getstation/desktop-app#93]
Unable to login in Telegram, Infinity loading and can't loading QR Code

**Comment by MichiMeyer** [comment]
Same here for Telegram and Whatsup equally. 
1) QR-Code not working in both
2) Telegram Login via User/Pass isn't loading after pressing login
Distro: Fedora 35

(Slack i.e. seems to be broken too. It is working to login but not able to finish loading the slack-deck. Infinity reloading)
