### ISSUE TITLE
Sign in via app issue

### ISSUE THREAD

**Issue by jendi-l** [getstation/desktop-app#96]
Trying to sign in to my Station app on a new device and get directed to an api.getstation.com page to log in, however, that page link is broken, leaving me unable to sign in to station. 

Error message for broken page: "This site can’t be reached. Check if there is a typo in api.getstation.com.
DNS_PROBE_FINISHED_NXDOMAIN'"

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
