### ISSUE TITLE
Whatsapp asking to update Chrome to work on Mac

### ISSUE THREAD

**Issue by RasmusSundHald** [getstation/desktop-app#97]
![image](https://user-images.githubusercontent.com/7437942/145584050-843a8399-2af9-4836-b041-245034e954d7.png)

**Comment by irfantony** [comment]
I got the same issue on Windows 10. 
I guess it's not related to Operating System, as I have 2 WhatsApp accounts running smooth on Rambox

**Comment by viktor44** [comment]
Fixed in [2.1.0](https://github.com/getstation/desktop-app/releases/tag/v2.1.0)
