### ISSUE TITLE
Discord not loading.

### ISSUE THREAD

**Issue by Mikee133** [getstation/desktop-app#98]
Logged into Discord and its just stuck on the loading screen.

The bug and feature request link also isn't working.  https://feedback.getstation.com/

**Comment by kaylamillerdev** [comment]
Same issue for me too. Just stuck on the logo spinning round and round

**Comment by Mikee133** [comment]
> Same issue for me too. Just stuck on the logo spinning round and round

It just doesn't work, sadly. There are other apps out there besides Shift. I went with Focos and it works great.

**Comment by d0ra-1h3-3xpl0ra** [comment]
Experiencing the same issue. Checked Focos Privacy Policy and figured that station is better. 
https://focos.io/privacy-policy/
