### ISSUE TITLE
Can't log in to my Google account

### ISSUE THREAD

**Issue by f-x1-1** [getstation/desktop-app#99]
“This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can try again to sign in .”

**Comment by jayverity** [comment]
I cant' log in to any of my 3 google accounts either, but I'm getting:

Missing required parameter: client_id

**Comment by kaylamillerdev** [comment]
I'm getting the same message about client_id

**Comment by josoal** [comment]
+1 here

**Comment by molhanecm** [comment]
Yes, some as for me, I think that the error is connected with this:
https://developers.google.com/identity/protocols/oauth2
I usually using Brave but I have switched to Edge and get the some error. 
The error happens for all applications connected with Google :-(

**Comment by oliviaschwerdt** [comment]
+1 to the above error: "Missing required parameter: client_id" when attempting to add my Google email/calendar accounts.

**Comment by getloriimdad** [comment]
The same issue, I can't log in to my Gmail due to "Missing required parameter: client_id."

**Comment by SebastianRau** [comment]
+1

**Comment by Emanuel-23** [comment]
+1

**Comment by psyferre** [comment]
+1

**Comment by abhinavmishra094** [comment]
+1

**Comment by getloriimdad** [comment]
Where are the developers???? The issue is 17 days old.

**Comment by aaronmeder** [comment]
Same here

**Comment by mark-fajardo** [comment]
Also encountering this issue.

**Comment by giampo91** [comment]
+1

**Comment by jojomillennium** [comment]
+1

**Comment by sgrosso** [comment]
+1

**Comment by jojomillennium** [comment]
You can add google calendar or gmail using the custom app, but there is an issue with the icon, and I have no idea how to change an app icon!

**Comment by cmd-werner-diers** [comment]
See https://github.com/getstation/desktop-app/issues/89

**Comment by timothymarois** [comment]
Same here. Cant log into gmail

**Comment by cotfas** [comment]
+1

**Comment by Darksk0pe** [comment]
please fix this :)

**Comment by getloriimdad** [comment]
I gave up on waiting and moved to Ferdi which is based on Franz. Probably better than Station anyway. Sad that Get Station has let this issue fester for so long.

**Comment by cotfas** [comment]
I used to use Singlebox and now I found Rambox which is interesting so far.

**Comment by jonathanwsl** [comment]
same issue,  and a new thread has opened up, I guess they are not interested

**Comment by zhouyijiaren** [comment]
+1
